// generated with gradle task `downloadWindowsZonesMapping`
package kotlinx.datetime.internal
internal val standardToWindows: Map<String, String> = mutableMapOf(
  "Africa/Abidjan" to "Greenwich Standard Time",
  "Africa/Accra" to "Greenwich Standard Time",
  "Africa/Addis_Ababa" to "E. Africa Standard Time",
  "Africa/Algiers" to "W. Central Africa Standard Time",
  "Africa/Asmera" to "E. Africa Standard Time",
  "Africa/Bamako" to "Greenwich Standard Time",
  "Africa/Bangui" to "W. Central Africa Standard Time",
  "Africa/Banjul" to "Greenwich Standard Time",
  "Africa/Bissau" to "Greenwich Standard Time",
  "Africa/Blantyre" to "South Africa Standard Time",
  "Africa/Brazzaville" to "W. Central Africa Standard Time",
  "Africa/Bujumbura" to "South Africa Standard Time",
  "Africa/Cairo" to "Egypt Standard Time",
  "Africa/Casablanca" to "Morocco Standard Time",
  "Africa/Ceuta" to "Romance Standard Time",
  "Africa/Conakry" to "Greenwich Standard Time",
  "Africa/Dakar" to "Greenwich Standard Time",
  "Africa/Dar_es_Salaam" to "E. Africa Standard Time",
  "Africa/Djibouti" to "E. Africa Standard Time",
  "Africa/Douala" to "W. Central Africa Standard Time",
  "Africa/El_Aaiun" to "Morocco Standard Time",
  "Africa/Freetown" to "Greenwich Standard Time",
  "Africa/Gaborone" to "South Africa Standard Time",
  "Africa/Harare" to "South Africa Standard Time",
  "Africa/Johannesburg" to "South Africa Standard Time",
  "Africa/Juba" to "South Sudan Standard Time",
  "Africa/Kampala" to "E. Africa Standard Time",
  "Africa/Khartoum" to "Sudan Standard Time",
  "Africa/Kigali" to "South Africa Standard Time",
  "Africa/Kinshasa" to "W. Central Africa Standard Time",
  "Africa/Lagos" to "W. Central Africa Standard Time",
  "Africa/Libreville" to "W. Central Africa Standard Time",
  "Africa/Lome" to "Greenwich Standard Time",
  "Africa/Luanda" to "W. Central Africa Standard Time",
  "Africa/Lubumbashi" to "South Africa Standard Time",
  "Africa/Lusaka" to "South Africa Standard Time",
  "Africa/Malabo" to "W. Central Africa Standard Time",
  "Africa/Maputo" to "South Africa Standard Time",
  "Africa/Maseru" to "South Africa Standard Time",
  "Africa/Mbabane" to "South Africa Standard Time",
  "Africa/Mogadishu" to "E. Africa Standard Time",
  "Africa/Monrovia" to "Greenwich Standard Time",
  "Africa/Nairobi" to "E. Africa Standard Time",
  "Africa/Ndjamena" to "W. Central Africa Standard Time",
  "Africa/Niamey" to "W. Central Africa Standard Time",
  "Africa/Nouakchott" to "Greenwich Standard Time",
  "Africa/Ouagadougou" to "Greenwich Standard Time",
  "Africa/Porto-Novo" to "W. Central Africa Standard Time",
  "Africa/Sao_Tome" to "Sao Tome Standard Time",
  "Africa/Tripoli" to "Libya Standard Time",
  "Africa/Tunis" to "W. Central Africa Standard Time",
  "Africa/Windhoek" to "Namibia Standard Time",
  "America/Adak" to "Aleutian Standard Time",
  "America/Anchorage" to "Alaskan Standard Time",
  "America/Anguilla" to "SA Western Standard Time",
  "America/Antigua" to "SA Western Standard Time",
  "America/Araguaina" to "Tocantins Standard Time",
  "America/Argentina/La_Rioja" to "Argentina Standard Time",
  "America/Argentina/Rio_Gallegos" to "Argentina Standard Time",
  "America/Argentina/Salta" to "Argentina Standard Time",
  "America/Argentina/San_Juan" to "Argentina Standard Time",
  "America/Argentina/San_Luis" to "Argentina Standard Time",
  "America/Argentina/Tucuman" to "Argentina Standard Time",
  "America/Argentina/Ushuaia" to "Argentina Standard Time",
  "America/Aruba" to "SA Western Standard Time",
  "America/Asuncion" to "Paraguay Standard Time",
  "America/Bahia" to "Bahia Standard Time",
  "America/Bahia_Banderas" to "Central Standard Time (Mexico)",
  "America/Barbados" to "SA Western Standard Time",
  "America/Belem" to "SA Eastern Standard Time",
  "America/Belize" to "Central America Standard Time",
  "America/Blanc-Sablon" to "SA Western Standard Time",
  "America/Boa_Vista" to "SA Western Standard Time",
  "America/Bogota" to "SA Pacific Standard Time",
  "America/Boise" to "Mountain Standard Time",
  "America/Buenos_Aires" to "Argentina Standard Time",
  "America/Cambridge_Bay" to "Mountain Standard Time",
  "America/Campo_Grande" to "Central Brazilian Standard Time",
  "America/Cancun" to "Eastern Standard Time (Mexico)",
  "America/Caracas" to "Venezuela Standard Time",
  "America/Catamarca" to "Argentina Standard Time",
  "America/Cayenne" to "SA Eastern Standard Time",
  "America/Cayman" to "SA Pacific Standard Time",
  "America/Chicago" to "Central Standard Time",
  "America/Chihuahua" to "Central Standard Time (Mexico)",
  "America/Ciudad_Juarez" to "Mountain Standard Time",
  "America/Coral_Harbour" to "SA Pacific Standard Time",
  "America/Cordoba" to "Argentina Standard Time",
  "America/Costa_Rica" to "Central America Standard Time",
  "America/Creston" to "US Mountain Standard Time",
  "America/Cuiaba" to "Central Brazilian Standard Time",
  "America/Curacao" to "SA Western Standard Time",
  "America/Danmarkshavn" to "Greenwich Standard Time",
  "America/Dawson" to "Yukon Standard Time",
  "America/Dawson_Creek" to "US Mountain Standard Time",
  "America/Denver" to "Mountain Standard Time",
  "America/Detroit" to "Eastern Standard Time",
  "America/Dominica" to "SA Western Standard Time",
  "America/Edmonton" to "Mountain Standard Time",
  "America/Eirunepe" to "SA Pacific Standard Time",
  "America/El_Salvador" to "Central America Standard Time",
  "America/Fort_Nelson" to "US Mountain Standard Time",
  "America/Fortaleza" to "SA Eastern Standard Time",
  "America/Glace_Bay" to "Atlantic Standard Time",
  "America/Godthab" to "Greenland Standard Time",
  "America/Goose_Bay" to "Atlantic Standard Time",
  "America/Grand_Turk" to "Turks And Caicos Standard Time",
  "America/Grenada" to "SA Western Standard Time",
  "America/Guadeloupe" to "SA Western Standard Time",
  "America/Guatemala" to "Central America Standard Time",
  "America/Guayaquil" to "SA Pacific Standard Time",
  "America/Guyana" to "SA Western Standard Time",
  "America/Halifax" to "Atlantic Standard Time",
  "America/Havana" to "Cuba Standard Time",
  "America/Hermosillo" to "US Mountain Standard Time",
  "America/Indiana/Knox" to "Central Standard Time",
  "America/Indiana/Marengo" to "US Eastern Standard Time",
  "America/Indiana/Petersburg" to "Eastern Standard Time",
  "America/Indiana/Tell_City" to "Central Standard Time",
  "America/Indiana/Vevay" to "US Eastern Standard Time",
  "America/Indiana/Vincennes" to "Eastern Standard Time",
  "America/Indiana/Winamac" to "Eastern Standard Time",
  "America/Indianapolis" to "US Eastern Standard Time",
  "America/Inuvik" to "Mountain Standard Time",
  "America/Iqaluit" to "Eastern Standard Time",
  "America/Jamaica" to "SA Pacific Standard Time",
  "America/Jujuy" to "Argentina Standard Time",
  "America/Juneau" to "Alaskan Standard Time",
  "America/Kentucky/Monticello" to "Eastern Standard Time",
  "America/Kralendijk" to "SA Western Standard Time",
  "America/La_Paz" to "SA Western Standard Time",
  "America/Lima" to "SA Pacific Standard Time",
  "America/Los_Angeles" to "Pacific Standard Time",
  "America/Louisville" to "Eastern Standard Time",
  "America/Lower_Princes" to "SA Western Standard Time",
  "America/Maceio" to "SA Eastern Standard Time",
  "America/Managua" to "Central America Standard Time",
  "America/Manaus" to "SA Western Standard Time",
  "America/Marigot" to "SA Western Standard Time",
  "America/Martinique" to "SA Western Standard Time",
  "America/Matamoros" to "Central Standard Time",
  "America/Mazatlan" to "Mountain Standard Time (Mexico)",
  "America/Mendoza" to "Argentina Standard Time",
  "America/Menominee" to "Central Standard Time",
  "America/Merida" to "Central Standard Time (Mexico)",
  "America/Metlakatla" to "Alaskan Standard Time",
  "America/Mexico_City" to "Central Standard Time (Mexico)",
  "America/Miquelon" to "Saint Pierre Standard Time",
  "America/Moncton" to "Atlantic Standard Time",
  "America/Monterrey" to "Central Standard Time (Mexico)",
  "America/Montevideo" to "Montevideo Standard Time",
  "America/Montserrat" to "SA Western Standard Time",
  "America/Nassau" to "Eastern Standard Time",
  "America/New_York" to "Eastern Standard Time",
  "America/Nome" to "Alaskan Standard Time",
  "America/Noronha" to "UTC-02",
  "America/North_Dakota/Beulah" to "Central Standard Time",
  "America/North_Dakota/Center" to "Central Standard Time",
  "America/North_Dakota/New_Salem" to "Central Standard Time",
  "America/Ojinaga" to "Central Standard Time",
  "America/Panama" to "SA Pacific Standard Time",
  "America/Paramaribo" to "SA Eastern Standard Time",
  "America/Phoenix" to "US Mountain Standard Time",
  "America/Port-au-Prince" to "Haiti Standard Time",
  "America/Port_of_Spain" to "SA Western Standard Time",
  "America/Porto_Velho" to "SA Western Standard Time",
  "America/Puerto_Rico" to "SA Western Standard Time",
  "America/Punta_Arenas" to "Magallanes Standard Time",
  "America/Rankin_Inlet" to "Central Standard Time",
  "America/Recife" to "SA Eastern Standard Time",
  "America/Regina" to "Canada Central Standard Time",
  "America/Resolute" to "Central Standard Time",
  "America/Rio_Branco" to "SA Pacific Standard Time",
  "America/Santarem" to "SA Eastern Standard Time",
  "America/Santiago" to "Pacific SA Standard Time",
  "America/Santo_Domingo" to "SA Western Standard Time",
  "America/Sao_Paulo" to "E. South America Standard Time",
  "America/Scoresbysund" to "Azores Standard Time",
  "America/Sitka" to "Alaskan Standard Time",
  "America/St_Barthelemy" to "SA Western Standard Time",
  "America/St_Johns" to "Newfoundland Standard Time",
  "America/St_Kitts" to "SA Western Standard Time",
  "America/St_Lucia" to "SA Western Standard Time",
  "America/St_Thomas" to "SA Western Standard Time",
  "America/St_Vincent" to "SA Western Standard Time",
  "America/Swift_Current" to "Canada Central Standard Time",
  "America/Tegucigalpa" to "Central America Standard Time",
  "America/Thule" to "Atlantic Standard Time",
  "America/Tijuana" to "Pacific Standard Time (Mexico)",
  "America/Toronto" to "Eastern Standard Time",
  "America/Tortola" to "SA Western Standard Time",
  "America/Vancouver" to "Pacific Standard Time",
  "America/Whitehorse" to "Yukon Standard Time",
  "America/Winnipeg" to "Central Standard Time",
  "America/Yakutat" to "Alaskan Standard Time",
  "Antarctica/Casey" to "Central Pacific Standard Time",
  "Antarctica/Davis" to "SE Asia Standard Time",
  "Antarctica/DumontDUrville" to "West Pacific Standard Time",
  "Antarctica/Macquarie" to "Tasmania Standard Time",
  "Antarctica/Mawson" to "West Asia Standard Time",
  "Antarctica/McMurdo" to "New Zealand Standard Time",
  "Antarctica/Palmer" to "SA Eastern Standard Time",
  "Antarctica/Rothera" to "SA Eastern Standard Time",
  "Antarctica/Syowa" to "E. Africa Standard Time",
  "Antarctica/Vostok" to "Central Asia Standard Time",
  "Arctic/Longyearbyen" to "W. Europe Standard Time",
  "Asia/Aden" to "Arab Standard Time",
  "Asia/Almaty" to "West Asia Standard Time",
  "Asia/Amman" to "Jordan Standard Time",
  "Asia/Anadyr" to "Russia Time Zone 11",
  "Asia/Aqtau" to "West Asia Standard Time",
  "Asia/Aqtobe" to "West Asia Standard Time",
  "Asia/Ashgabat" to "West Asia Standard Time",
  "Asia/Atyrau" to "West Asia Standard Time",
  "Asia/Baghdad" to "Arabic Standard Time",
  "Asia/Bahrain" to "Arab Standard Time",
  "Asia/Baku" to "Azerbaijan Standard Time",
  "Asia/Bangkok" to "SE Asia Standard Time",
  "Asia/Barnaul" to "Altai Standard Time",
  "Asia/Beirut" to "Middle East Standard Time",
  "Asia/Bishkek" to "Central Asia Standard Time",
  "Asia/Brunei" to "Singapore Standard Time",
  "Asia/Calcutta" to "India Standard Time",
  "Asia/Chita" to "Transbaikal Standard Time",
  "Asia/Choibalsan" to "Ulaanbaatar Standard Time",
  "Asia/Colombo" to "Sri Lanka Standard Time",
  "Asia/Damascus" to "Syria Standard Time",
  "Asia/Dhaka" to "Bangladesh Standard Time",
  "Asia/Dili" to "Tokyo Standard Time",
  "Asia/Dubai" to "Arabian Standard Time",
  "Asia/Dushanbe" to "West Asia Standard Time",
  "Asia/Famagusta" to "GTB Standard Time",
  "Asia/Gaza" to "West Bank Standard Time",
  "Asia/Hebron" to "West Bank Standard Time",
  "Asia/Hong_Kong" to "China Standard Time",
  "Asia/Hovd" to "W. Mongolia Standard Time",
  "Asia/Irkutsk" to "North Asia East Standard Time",
  "Asia/Jakarta" to "SE Asia Standard Time",
  "Asia/Jayapura" to "Tokyo Standard Time",
  "Asia/Jerusalem" to "Israel Standard Time",
  "Asia/Kabul" to "Afghanistan Standard Time",
  "Asia/Kamchatka" to "Russia Time Zone 11",
  "Asia/Karachi" to "Pakistan Standard Time",
  "Asia/Katmandu" to "Nepal Standard Time",
  "Asia/Khandyga" to "Yakutsk Standard Time",
  "Asia/Krasnoyarsk" to "North Asia Standard Time",
  "Asia/Kuala_Lumpur" to "Singapore Standard Time",
  "Asia/Kuching" to "Singapore Standard Time",
  "Asia/Kuwait" to "Arab Standard Time",
  "Asia/Macau" to "China Standard Time",
  "Asia/Magadan" to "Magadan Standard Time",
  "Asia/Makassar" to "Singapore Standard Time",
  "Asia/Manila" to "Singapore Standard Time",
  "Asia/Muscat" to "Arabian Standard Time",
  "Asia/Nicosia" to "GTB Standard Time",
  "Asia/Novokuznetsk" to "North Asia Standard Time",
  "Asia/Novosibirsk" to "N. Central Asia Standard Time",
  "Asia/Omsk" to "Omsk Standard Time",
  "Asia/Oral" to "West Asia Standard Time",
  "Asia/Phnom_Penh" to "SE Asia Standard Time",
  "Asia/Pontianak" to "SE Asia Standard Time",
  "Asia/Pyongyang" to "North Korea Standard Time",
  "Asia/Qatar" to "Arab Standard Time",
  "Asia/Qostanay" to "West Asia Standard Time",
  "Asia/Qyzylorda" to "Qyzylorda Standard Time",
  "Asia/Rangoon" to "Myanmar Standard Time",
  "Asia/Riyadh" to "Arab Standard Time",
  "Asia/Saigon" to "SE Asia Standard Time",
  "Asia/Sakhalin" to "Sakhalin Standard Time",
  "Asia/Samarkand" to "West Asia Standard Time",
  "Asia/Seoul" to "Korea Standard Time",
  "Asia/Shanghai" to "China Standard Time",
  "Asia/Singapore" to "Singapore Standard Time",
  "Asia/Srednekolymsk" to "Russia Time Zone 10",
  "Asia/Taipei" to "Taipei Standard Time",
  "Asia/Tashkent" to "West Asia Standard Time",
  "Asia/Tbilisi" to "Georgian Standard Time",
  "Asia/Tehran" to "Iran Standard Time",
  "Asia/Thimphu" to "Bangladesh Standard Time",
  "Asia/Tokyo" to "Tokyo Standard Time",
  "Asia/Tomsk" to "Tomsk Standard Time",
  "Asia/Ulaanbaatar" to "Ulaanbaatar Standard Time",
  "Asia/Urumqi" to "Central Asia Standard Time",
  "Asia/Ust-Nera" to "Vladivostok Standard Time",
  "Asia/Vientiane" to "SE Asia Standard Time",
  "Asia/Vladivostok" to "Vladivostok Standard Time",
  "Asia/Yakutsk" to "Yakutsk Standard Time",
  "Asia/Yekaterinburg" to "Ekaterinburg Standard Time",
  "Asia/Yerevan" to "Caucasus Standard Time",
  "Atlantic/Azores" to "Azores Standard Time",
  "Atlantic/Bermuda" to "Atlantic Standard Time",
  "Atlantic/Canary" to "GMT Standard Time",
  "Atlantic/Cape_Verde" to "Cape Verde Standard Time",
  "Atlantic/Faeroe" to "GMT Standard Time",
  "Atlantic/Madeira" to "GMT Standard Time",
  "Atlantic/Reykjavik" to "Greenwich Standard Time",
  "Atlantic/South_Georgia" to "UTC-02",
  "Atlantic/St_Helena" to "Greenwich Standard Time",
  "Atlantic/Stanley" to "SA Eastern Standard Time",
  "Australia/Adelaide" to "Cen. Australia Standard Time",
  "Australia/Brisbane" to "E. Australia Standard Time",
  "Australia/Broken_Hill" to "Cen. Australia Standard Time",
  "Australia/Darwin" to "AUS Central Standard Time",
  "Australia/Eucla" to "Aus Central W. Standard Time",
  "Australia/Hobart" to "Tasmania Standard Time",
  "Australia/Lindeman" to "E. Australia Standard Time",
  "Australia/Lord_Howe" to "Lord Howe Standard Time",
  "Australia/Melbourne" to "AUS Eastern Standard Time",
  "Australia/Perth" to "W. Australia Standard Time",
  "Australia/Sydney" to "AUS Eastern Standard Time",
  "CST6CDT" to "Central Standard Time",
  "EST5EDT" to "Eastern Standard Time",
  "Etc/GMT" to "UTC",
  "Etc/GMT+1" to "Cape Verde Standard Time",
  "Etc/GMT+10" to "Hawaiian Standard Time",
  "Etc/GMT+11" to "UTC-11",
  "Etc/GMT+12" to "Dateline Standard Time",
  "Etc/GMT+2" to "UTC-02",
  "Etc/GMT+3" to "SA Eastern Standard Time",
  "Etc/GMT+4" to "SA Western Standard Time",
  "Etc/GMT+5" to "SA Pacific Standard Time",
  "Etc/GMT+6" to "Central America Standard Time",
  "Etc/GMT+7" to "US Mountain Standard Time",
  "Etc/GMT+8" to "UTC-08",
  "Etc/GMT+9" to "UTC-09",
  "Etc/GMT-1" to "W. Central Africa Standard Time",
  "Etc/GMT-10" to "West Pacific Standard Time",
  "Etc/GMT-11" to "Central Pacific Standard Time",
  "Etc/GMT-12" to "UTC+12",
  "Etc/GMT-13" to "UTC+13",
  "Etc/GMT-14" to "Line Islands Standard Time",
  "Etc/GMT-2" to "South Africa Standard Time",
  "Etc/GMT-3" to "E. Africa Standard Time",
  "Etc/GMT-4" to "Arabian Standard Time",
  "Etc/GMT-5" to "West Asia Standard Time",
  "Etc/GMT-6" to "Central Asia Standard Time",
  "Etc/GMT-7" to "SE Asia Standard Time",
  "Etc/GMT-8" to "Singapore Standard Time",
  "Etc/GMT-9" to "Tokyo Standard Time",
  "Etc/UTC" to "UTC",
  "Europe/Amsterdam" to "W. Europe Standard Time",
  "Europe/Andorra" to "W. Europe Standard Time",
  "Europe/Astrakhan" to "Astrakhan Standard Time",
  "Europe/Athens" to "GTB Standard Time",
  "Europe/Belgrade" to "Central Europe Standard Time",
  "Europe/Berlin" to "W. Europe Standard Time",
  "Europe/Bratislava" to "Central Europe Standard Time",
  "Europe/Brussels" to "Romance Standard Time",
  "Europe/Bucharest" to "GTB Standard Time",
  "Europe/Budapest" to "Central Europe Standard Time",
  "Europe/Busingen" to "W. Europe Standard Time",
  "Europe/Chisinau" to "E. Europe Standard Time",
  "Europe/Copenhagen" to "Romance Standard Time",
  "Europe/Dublin" to "GMT Standard Time",
  "Europe/Gibraltar" to "W. Europe Standard Time",
  "Europe/Guernsey" to "GMT Standard Time",
  "Europe/Helsinki" to "FLE Standard Time",
  "Europe/Isle_of_Man" to "GMT Standard Time",
  "Europe/Istanbul" to "Turkey Standard Time",
  "Europe/Jersey" to "GMT Standard Time",
  "Europe/Kaliningrad" to "Kaliningrad Standard Time",
  "Europe/Kiev" to "FLE Standard Time",
  "Europe/Kirov" to "Russian Standard Time",
  "Europe/Lisbon" to "GMT Standard Time",
  "Europe/Ljubljana" to "Central Europe Standard Time",
  "Europe/London" to "GMT Standard Time",
  "Europe/Luxembourg" to "W. Europe Standard Time",
  "Europe/Madrid" to "Romance Standard Time",
  "Europe/Malta" to "W. Europe Standard Time",
  "Europe/Mariehamn" to "FLE Standard Time",
  "Europe/Minsk" to "Belarus Standard Time",
  "Europe/Monaco" to "W. Europe Standard Time",
  "Europe/Moscow" to "Russian Standard Time",
  "Europe/Oslo" to "W. Europe Standard Time",
  "Europe/Paris" to "Romance Standard Time",
  "Europe/Podgorica" to "Central Europe Standard Time",
  "Europe/Prague" to "Central Europe Standard Time",
  "Europe/Riga" to "FLE Standard Time",
  "Europe/Rome" to "W. Europe Standard Time",
  "Europe/Samara" to "Russia Time Zone 3",
  "Europe/San_Marino" to "W. Europe Standard Time",
  "Europe/Sarajevo" to "Central European Standard Time",
  "Europe/Saratov" to "Saratov Standard Time",
  "Europe/Simferopol" to "Russian Standard Time",
  "Europe/Skopje" to "Central European Standard Time",
  "Europe/Sofia" to "FLE Standard Time",
  "Europe/Stockholm" to "W. Europe Standard Time",
  "Europe/Tallinn" to "FLE Standard Time",
  "Europe/Tirane" to "Central Europe Standard Time",
  "Europe/Ulyanovsk" to "Astrakhan Standard Time",
  "Europe/Vaduz" to "W. Europe Standard Time",
  "Europe/Vatican" to "W. Europe Standard Time",
  "Europe/Vienna" to "W. Europe Standard Time",
  "Europe/Vilnius" to "FLE Standard Time",
  "Europe/Volgograd" to "Volgograd Standard Time",
  "Europe/Warsaw" to "Central European Standard Time",
  "Europe/Zagreb" to "Central European Standard Time",
  "Europe/Zurich" to "W. Europe Standard Time",
  "Indian/Antananarivo" to "E. Africa Standard Time",
  "Indian/Chagos" to "Central Asia Standard Time",
  "Indian/Christmas" to "SE Asia Standard Time",
  "Indian/Cocos" to "Myanmar Standard Time",
  "Indian/Comoro" to "E. Africa Standard Time",
  "Indian/Kerguelen" to "West Asia Standard Time",
  "Indian/Mahe" to "Mauritius Standard Time",
  "Indian/Maldives" to "West Asia Standard Time",
  "Indian/Mauritius" to "Mauritius Standard Time",
  "Indian/Mayotte" to "E. Africa Standard Time",
  "Indian/Reunion" to "Mauritius Standard Time",
  "MST7MDT" to "Mountain Standard Time",
  "PST8PDT" to "Pacific Standard Time",
  "Pacific/Apia" to "Samoa Standard Time",
  "Pacific/Auckland" to "New Zealand Standard Time",
  "Pacific/Bougainville" to "Bougainville Standard Time",
  "Pacific/Chatham" to "Chatham Islands Standard Time",
  "Pacific/Easter" to "Easter Island Standard Time",
  "Pacific/Efate" to "Central Pacific Standard Time",
  "Pacific/Enderbury" to "UTC+13",
  "Pacific/Fakaofo" to "UTC+13",
  "Pacific/Fiji" to "Fiji Standard Time",
  "Pacific/Funafuti" to "UTC+12",
  "Pacific/Galapagos" to "Central America Standard Time",
  "Pacific/Gambier" to "UTC-09",
  "Pacific/Guadalcanal" to "Central Pacific Standard Time",
  "Pacific/Guam" to "West Pacific Standard Time",
  "Pacific/Honolulu" to "Hawaiian Standard Time",
  "Pacific/Kiritimati" to "Line Islands Standard Time",
  "Pacific/Kosrae" to "Central Pacific Standard Time",
  "Pacific/Kwajalein" to "UTC+12",
  "Pacific/Majuro" to "UTC+12",
  "Pacific/Marquesas" to "Marquesas Standard Time",
  "Pacific/Midway" to "UTC-11",
  "Pacific/Nauru" to "UTC+12",
  "Pacific/Niue" to "UTC-11",
  "Pacific/Norfolk" to "Norfolk Standard Time",
  "Pacific/Noumea" to "Central Pacific Standard Time",
  "Pacific/Pago_Pago" to "UTC-11",
  "Pacific/Palau" to "Tokyo Standard Time",
  "Pacific/Pitcairn" to "UTC-08",
  "Pacific/Ponape" to "Central Pacific Standard Time",
  "Pacific/Port_Moresby" to "West Pacific Standard Time",
  "Pacific/Rarotonga" to "Hawaiian Standard Time",
  "Pacific/Saipan" to "West Pacific Standard Time",
  "Pacific/Tahiti" to "Hawaiian Standard Time",
  "Pacific/Tarawa" to "UTC+12",
  "Pacific/Tongatapu" to "Tonga Standard Time",
  "Pacific/Truk" to "West Pacific Standard Time",
  "Pacific/Wake" to "UTC+12",
  "Pacific/Wallis" to "UTC+12",
  "UTC" to "UTC",
)
internal val windowsToStandard: Map<String, String> = mutableMapOf(
  "AUS Central Standard Time" to "Australia/Darwin",
  "AUS Eastern Standard Time" to "Australia/Sydney",
  "Afghanistan Standard Time" to "Asia/Kabul",
  "Alaskan Standard Time" to "America/Anchorage",
  "Aleutian Standard Time" to "America/Adak",
  "Altai Standard Time" to "Asia/Barnaul",
  "Arab Standard Time" to "Asia/Riyadh",
  "Arabian Standard Time" to "Asia/Dubai",
  "Arabic Standard Time" to "Asia/Baghdad",
  "Argentina Standard Time" to "America/Buenos_Aires",
  "Astrakhan Standard Time" to "Europe/Astrakhan",
  "Atlantic Standard Time" to "America/Halifax",
  "Aus Central W. Standard Time" to "Australia/Eucla",
  "Azerbaijan Standard Time" to "Asia/Baku",
  "Azores Standard Time" to "Atlantic/Azores",
  "Bahia Standard Time" to "America/Bahia",
  "Bangladesh Standard Time" to "Asia/Dhaka",
  "Belarus Standard Time" to "Europe/Minsk",
  "Bougainville Standard Time" to "Pacific/Bougainville",
  "Canada Central Standard Time" to "America/Regina",
  "Cape Verde Standard Time" to "Atlantic/Cape_Verde",
  "Caucasus Standard Time" to "Asia/Yerevan",
  "Cen. Australia Standard Time" to "Australia/Adelaide",
  "Central America Standard Time" to "America/Guatemala",
  "Central Asia Standard Time" to "Asia/Bishkek",
  "Central Brazilian Standard Time" to "America/Cuiaba",
  "Central Europe Standard Time" to "Europe/Budapest",
  "Central European Standard Time" to "Europe/Warsaw",
  "Central Pacific Standard Time" to "Pacific/Guadalcanal",
  "Central Standard Time" to "America/Chicago",
  "Central Standard Time (Mexico)" to "America/Mexico_City",
  "Chatham Islands Standard Time" to "Pacific/Chatham",
  "China Standard Time" to "Asia/Shanghai",
  "Cuba Standard Time" to "America/Havana",
  "Dateline Standard Time" to "Etc/GMT+12",
  "E. Africa Standard Time" to "Africa/Nairobi",
  "E. Australia Standard Time" to "Australia/Brisbane",
  "E. Europe Standard Time" to "Europe/Chisinau",
  "E. South America Standard Time" to "America/Sao_Paulo",
  "Easter Island Standard Time" to "Pacific/Easter",
  "Eastern Standard Time" to "America/New_York",
  "Eastern Standard Time (Mexico)" to "America/Cancun",
  "Egypt Standard Time" to "Africa/Cairo",
  "Ekaterinburg Standard Time" to "Asia/Yekaterinburg",
  "FLE Standard Time" to "Europe/Kiev",
  "Fiji Standard Time" to "Pacific/Fiji",
  "GMT Standard Time" to "Europe/London",
  "GTB Standard Time" to "Europe/Bucharest",
  "Georgian Standard Time" to "Asia/Tbilisi",
  "Greenland Standard Time" to "America/Godthab",
  "Greenwich Standard Time" to "Atlantic/Reykjavik",
  "Haiti Standard Time" to "America/Port-au-Prince",
  "Hawaiian Standard Time" to "Pacific/Honolulu",
  "India Standard Time" to "Asia/Calcutta",
  "Iran Standard Time" to "Asia/Tehran",
  "Israel Standard Time" to "Asia/Jerusalem",
  "Jordan Standard Time" to "Asia/Amman",
  "Kaliningrad Standard Time" to "Europe/Kaliningrad",
  "Korea Standard Time" to "Asia/Seoul",
  "Libya Standard Time" to "Africa/Tripoli",
  "Line Islands Standard Time" to "Pacific/Kiritimati",
  "Lord Howe Standard Time" to "Australia/Lord_Howe",
  "Magadan Standard Time" to "Asia/Magadan",
  "Magallanes Standard Time" to "America/Punta_Arenas",
  "Marquesas Standard Time" to "Pacific/Marquesas",
  "Mauritius Standard Time" to "Indian/Mauritius",
  "Middle East Standard Time" to "Asia/Beirut",
  "Montevideo Standard Time" to "America/Montevideo",
  "Morocco Standard Time" to "Africa/Casablanca",
  "Mountain Standard Time" to "America/Denver",
  "Mountain Standard Time (Mexico)" to "America/Mazatlan",
  "Myanmar Standard Time" to "Asia/Rangoon",
  "N. Central Asia Standard Time" to "Asia/Novosibirsk",
  "Namibia Standard Time" to "Africa/Windhoek",
  "Nepal Standard Time" to "Asia/Katmandu",
  "New Zealand Standard Time" to "Pacific/Auckland",
  "Newfoundland Standard Time" to "America/St_Johns",
  "Norfolk Standard Time" to "Pacific/Norfolk",
  "North Asia East Standard Time" to "Asia/Irkutsk",
  "North Asia Standard Time" to "Asia/Krasnoyarsk",
  "North Korea Standard Time" to "Asia/Pyongyang",
  "Omsk Standard Time" to "Asia/Omsk",
  "Pacific SA Standard Time" to "America/Santiago",
  "Pacific Standard Time" to "America/Los_Angeles",
  "Pacific Standard Time (Mexico)" to "America/Tijuana",
  "Pakistan Standard Time" to "Asia/Karachi",
  "Paraguay Standard Time" to "America/Asuncion",
  "Qyzylorda Standard Time" to "Asia/Qyzylorda",
  "Romance Standard Time" to "Europe/Paris",
  "Russia Time Zone 10" to "Asia/Srednekolymsk",
  "Russia Time Zone 11" to "Asia/Kamchatka",
  "Russia Time Zone 3" to "Europe/Samara",
  "Russian Standard Time" to "Europe/Moscow",
  "SA Eastern Standard Time" to "America/Cayenne",
  "SA Pacific Standard Time" to "America/Bogota",
  "SA Western Standard Time" to "America/La_Paz",
  "SE Asia Standard Time" to "Asia/Bangkok",
  "Saint Pierre Standard Time" to "America/Miquelon",
  "Sakhalin Standard Time" to "Asia/Sakhalin",
  "Samoa Standard Time" to "Pacific/Apia",
  "Sao Tome Standard Time" to "Africa/Sao_Tome",
  "Saratov Standard Time" to "Europe/Saratov",
  "Singapore Standard Time" to "Asia/Singapore",
  "South Africa Standard Time" to "Africa/Johannesburg",
  "South Sudan Standard Time" to "Africa/Juba",
  "Sri Lanka Standard Time" to "Asia/Colombo",
  "Sudan Standard Time" to "Africa/Khartoum",
  "Syria Standard Time" to "Asia/Damascus",
  "Taipei Standard Time" to "Asia/Taipei",
  "Tasmania Standard Time" to "Australia/Hobart",
  "Tocantins Standard Time" to "America/Araguaina",
  "Tokyo Standard Time" to "Asia/Tokyo",
  "Tomsk Standard Time" to "Asia/Tomsk",
  "Tonga Standard Time" to "Pacific/Tongatapu",
  "Transbaikal Standard Time" to "Asia/Chita",
  "Turkey Standard Time" to "Europe/Istanbul",
  "Turks And Caicos Standard Time" to "America/Grand_Turk",
  "US Eastern Standard Time" to "America/Indianapolis",
  "US Mountain Standard Time" to "America/Phoenix",
  "UTC" to "UTC",
  "UTC+12" to "Etc/GMT-12",
  "UTC+13" to "Etc/GMT-13",
  "UTC-02" to "Etc/GMT+2",
  "UTC-08" to "Etc/GMT+8",
  "UTC-09" to "Etc/GMT+9",
  "UTC-11" to "Etc/GMT+11",
  "Ulaanbaatar Standard Time" to "Asia/Ulaanbaatar",
  "Venezuela Standard Time" to "America/Caracas",
  "Vladivostok Standard Time" to "Asia/Vladivostok",
  "Volgograd Standard Time" to "Europe/Volgograd",
  "W. Australia Standard Time" to "Australia/Perth",
  "W. Central Africa Standard Time" to "Africa/Lagos",
  "W. Europe Standard Time" to "Europe/Berlin",
  "W. Mongolia Standard Time" to "Asia/Hovd",
  "West Asia Standard Time" to "Asia/Tashkent",
  "West Bank Standard Time" to "Asia/Hebron",
  "West Pacific Standard Time" to "Pacific/Port_Moresby",
  "Yakutsk Standard Time" to "Asia/Yakutsk",
  "Yukon Standard Time" to "America/Whitehorse",
)
