// generated with gradle task `downloadWindowsZonesMapping`
#include <unordered_map>
#include <string>
static const std::unordered_map<std::string, std::string> standard_to_windows = {
	{ "Africa/Abidjan", "Greenwich Standard Time" },
	{ "Africa/Accra", "Greenwich Standard Time" },
	{ "Africa/Addis_Ababa", "E. Africa Standard Time" },
	{ "Africa/Algiers", "W. Central Africa Standard Time" },
	{ "Africa/Asmera", "E. Africa Standard Time" },
	{ "Africa/Bamako", "Greenwich Standard Time" },
	{ "Africa/Bangui", "W. Central Africa Standard Time" },
	{ "Africa/Banjul", "Greenwich Standard Time" },
	{ "Africa/Bissau", "Greenwich Standard Time" },
	{ "Africa/Blantyre", "South Africa Standard Time" },
	{ "Africa/Brazzaville", "W. Central Africa Standard Time" },
	{ "Africa/Bujumbura", "South Africa Standard Time" },
	{ "Africa/Cairo", "Egypt Standard Time" },
	{ "Africa/Casablanca", "Morocco Standard Time" },
	{ "Africa/Ceuta", "Romance Standard Time" },
	{ "Africa/Conakry", "Greenwich Standard Time" },
	{ "Africa/Dakar", "Greenwich Standard Time" },
	{ "Africa/Dar_es_Salaam", "E. Africa Standard Time" },
	{ "Africa/Djibouti", "E. Africa Standard Time" },
	{ "Africa/Douala", "W. Central Africa Standard Time" },
	{ "Africa/El_Aaiun", "Morocco Standard Time" },
	{ "Africa/Freetown", "Greenwich Standard Time" },
	{ "Africa/Gaborone", "South Africa Standard Time" },
	{ "Africa/Harare", "South Africa Standard Time" },
	{ "Africa/Johannesburg", "South Africa Standard Time" },
	{ "Africa/Juba", "E. Africa Standard Time" },
	{ "Africa/Kampala", "E. Africa Standard Time" },
	{ "Africa/Khartoum", "Sudan Standard Time" },
	{ "Africa/Kigali", "South Africa Standard Time" },
	{ "Africa/Kinshasa", "W. Central Africa Standard Time" },
	{ "Africa/Lagos", "W. Central Africa Standard Time" },
	{ "Africa/Libreville", "W. Central Africa Standard Time" },
	{ "Africa/Lome", "Greenwich Standard Time" },
	{ "Africa/Luanda", "W. Central Africa Standard Time" },
	{ "Africa/Lubumbashi", "South Africa Standard Time" },
	{ "Africa/Lusaka", "South Africa Standard Time" },
	{ "Africa/Malabo", "W. Central Africa Standard Time" },
	{ "Africa/Maputo", "South Africa Standard Time" },
	{ "Africa/Maseru", "South Africa Standard Time" },
	{ "Africa/Mbabane", "South Africa Standard Time" },
	{ "Africa/Mogadishu", "E. Africa Standard Time" },
	{ "Africa/Monrovia", "Greenwich Standard Time" },
	{ "Africa/Nairobi", "E. Africa Standard Time" },
	{ "Africa/Ndjamena", "W. Central Africa Standard Time" },
	{ "Africa/Niamey", "W. Central Africa Standard Time" },
	{ "Africa/Nouakchott", "Greenwich Standard Time" },
	{ "Africa/Ouagadougou", "Greenwich Standard Time" },
	{ "Africa/Porto-Novo", "W. Central Africa Standard Time" },
	{ "Africa/Sao_Tome", "Sao Tome Standard Time" },
	{ "Africa/Tripoli", "Libya Standard Time" },
	{ "Africa/Tunis", "W. Central Africa Standard Time" },
	{ "Africa/Windhoek", "Namibia Standard Time" },
	{ "America/Adak", "Aleutian Standard Time" },
	{ "America/Anchorage", "Alaskan Standard Time" },
	{ "America/Anguilla", "SA Western Standard Time" },
	{ "America/Antigua", "SA Western Standard Time" },
	{ "America/Araguaina", "Tocantins Standard Time" },
	{ "America/Argentina/La_Rioja", "Argentina Standard Time" },
	{ "America/Argentina/Rio_Gallegos", "Argentina Standard Time" },
	{ "America/Argentina/Salta", "Argentina Standard Time" },
	{ "America/Argentina/San_Juan", "Argentina Standard Time" },
	{ "America/Argentina/San_Luis", "Argentina Standard Time" },
	{ "America/Argentina/Tucuman", "Argentina Standard Time" },
	{ "America/Argentina/Ushuaia", "Argentina Standard Time" },
	{ "America/Aruba", "SA Western Standard Time" },
	{ "America/Asuncion", "Paraguay Standard Time" },
	{ "America/Bahia", "Bahia Standard Time" },
	{ "America/Bahia_Banderas", "Central Standard Time (Mexico)" },
	{ "America/Barbados", "SA Western Standard Time" },
	{ "America/Belem", "SA Eastern Standard Time" },
	{ "America/Belize", "Central America Standard Time" },
	{ "America/Blanc-Sablon", "SA Western Standard Time" },
	{ "America/Boa_Vista", "SA Western Standard Time" },
	{ "America/Bogota", "SA Pacific Standard Time" },
	{ "America/Boise", "Mountain Standard Time" },
	{ "America/Buenos_Aires", "Argentina Standard Time" },
	{ "America/Cambridge_Bay", "Mountain Standard Time" },
	{ "America/Campo_Grande", "Central Brazilian Standard Time" },
	{ "America/Cancun", "Eastern Standard Time (Mexico)" },
	{ "America/Caracas", "Venezuela Standard Time" },
	{ "America/Catamarca", "Argentina Standard Time" },
	{ "America/Cayenne", "SA Eastern Standard Time" },
	{ "America/Cayman", "SA Pacific Standard Time" },
	{ "America/Chicago", "Central Standard Time" },
	{ "America/Chihuahua", "Mountain Standard Time (Mexico)" },
	{ "America/Coral_Harbour", "SA Pacific Standard Time" },
	{ "America/Cordoba", "Argentina Standard Time" },
	{ "America/Costa_Rica", "Central America Standard Time" },
	{ "America/Creston", "US Mountain Standard Time" },
	{ "America/Cuiaba", "Central Brazilian Standard Time" },
	{ "America/Curacao", "SA Western Standard Time" },
	{ "America/Danmarkshavn", "UTC" },
	{ "America/Dawson", "Pacific Standard Time" },
	{ "America/Dawson_Creek", "US Mountain Standard Time" },
	{ "America/Denver", "Mountain Standard Time" },
	{ "America/Detroit", "Eastern Standard Time" },
	{ "America/Dominica", "SA Western Standard Time" },
	{ "America/Edmonton", "Mountain Standard Time" },
	{ "America/Eirunepe", "SA Pacific Standard Time" },
	{ "America/El_Salvador", "Central America Standard Time" },
	{ "America/Fort_Nelson", "US Mountain Standard Time" },
	{ "America/Fortaleza", "SA Eastern Standard Time" },
	{ "America/Glace_Bay", "Atlantic Standard Time" },
	{ "America/Godthab", "Greenland Standard Time" },
	{ "America/Goose_Bay", "Atlantic Standard Time" },
	{ "America/Grand_Turk", "Turks And Caicos Standard Time" },
	{ "America/Grenada", "SA Western Standard Time" },
	{ "America/Guadeloupe", "SA Western Standard Time" },
	{ "America/Guatemala", "Central America Standard Time" },
	{ "America/Guayaquil", "SA Pacific Standard Time" },
	{ "America/Guyana", "SA Western Standard Time" },
	{ "America/Halifax", "Atlantic Standard Time" },
	{ "America/Havana", "Cuba Standard Time" },
	{ "America/Hermosillo", "US Mountain Standard Time" },
	{ "America/Indiana/Knox", "Central Standard Time" },
	{ "America/Indiana/Marengo", "US Eastern Standard Time" },
	{ "America/Indiana/Petersburg", "Eastern Standard Time" },
	{ "America/Indiana/Tell_City", "Central Standard Time" },
	{ "America/Indiana/Vevay", "US Eastern Standard Time" },
	{ "America/Indiana/Vincennes", "Eastern Standard Time" },
	{ "America/Indiana/Winamac", "Eastern Standard Time" },
	{ "America/Indianapolis", "US Eastern Standard Time" },
	{ "America/Inuvik", "Mountain Standard Time" },
	{ "America/Iqaluit", "Eastern Standard Time" },
	{ "America/Jamaica", "SA Pacific Standard Time" },
	{ "America/Jujuy", "Argentina Standard Time" },
	{ "America/Juneau", "Alaskan Standard Time" },
	{ "America/Kentucky/Monticello", "Eastern Standard Time" },
	{ "America/Kralendijk", "SA Western Standard Time" },
	{ "America/La_Paz", "SA Western Standard Time" },
	{ "America/Lima", "SA Pacific Standard Time" },
	{ "America/Los_Angeles", "Pacific Standard Time" },
	{ "America/Louisville", "Eastern Standard Time" },
	{ "America/Lower_Princes", "SA Western Standard Time" },
	{ "America/Maceio", "SA Eastern Standard Time" },
	{ "America/Managua", "Central America Standard Time" },
	{ "America/Manaus", "SA Western Standard Time" },
	{ "America/Marigot", "SA Western Standard Time" },
	{ "America/Martinique", "SA Western Standard Time" },
	{ "America/Matamoros", "Central Standard Time" },
	{ "America/Mazatlan", "Mountain Standard Time (Mexico)" },
	{ "America/Mendoza", "Argentina Standard Time" },
	{ "America/Menominee", "Central Standard Time" },
	{ "America/Merida", "Central Standard Time (Mexico)" },
	{ "America/Metlakatla", "Alaskan Standard Time" },
	{ "America/Mexico_City", "Central Standard Time (Mexico)" },
	{ "America/Miquelon", "Saint Pierre Standard Time" },
	{ "America/Moncton", "Atlantic Standard Time" },
	{ "America/Monterrey", "Central Standard Time (Mexico)" },
	{ "America/Montevideo", "Montevideo Standard Time" },
	{ "America/Montreal", "Eastern Standard Time" },
	{ "America/Montserrat", "SA Western Standard Time" },
	{ "America/Nassau", "Eastern Standard Time" },
	{ "America/New_York", "Eastern Standard Time" },
	{ "America/Nipigon", "Eastern Standard Time" },
	{ "America/Nome", "Alaskan Standard Time" },
	{ "America/Noronha", "UTC-02" },
	{ "America/North_Dakota/Beulah", "Central Standard Time" },
	{ "America/North_Dakota/Center", "Central Standard Time" },
	{ "America/North_Dakota/New_Salem", "Central Standard Time" },
	{ "America/Ojinaga", "Mountain Standard Time" },
	{ "America/Panama", "SA Pacific Standard Time" },
	{ "America/Pangnirtung", "Eastern Standard Time" },
	{ "America/Paramaribo", "SA Eastern Standard Time" },
	{ "America/Phoenix", "US Mountain Standard Time" },
	{ "America/Port-au-Prince", "Haiti Standard Time" },
	{ "America/Port_of_Spain", "SA Western Standard Time" },
	{ "America/Porto_Velho", "SA Western Standard Time" },
	{ "America/Puerto_Rico", "SA Western Standard Time" },
	{ "America/Punta_Arenas", "Magallanes Standard Time" },
	{ "America/Rainy_River", "Central Standard Time" },
	{ "America/Rankin_Inlet", "Central Standard Time" },
	{ "America/Recife", "SA Eastern Standard Time" },
	{ "America/Regina", "Canada Central Standard Time" },
	{ "America/Resolute", "Central Standard Time" },
	{ "America/Rio_Branco", "SA Pacific Standard Time" },
	{ "America/Santa_Isabel", "Pacific Standard Time (Mexico)" },
	{ "America/Santarem", "SA Eastern Standard Time" },
	{ "America/Santiago", "Pacific SA Standard Time" },
	{ "America/Santo_Domingo", "SA Western Standard Time" },
	{ "America/Sao_Paulo", "E. South America Standard Time" },
	{ "America/Scoresbysund", "Azores Standard Time" },
	{ "America/Sitka", "Alaskan Standard Time" },
	{ "America/St_Barthelemy", "SA Western Standard Time" },
	{ "America/St_Johns", "Newfoundland Standard Time" },
	{ "America/St_Kitts", "SA Western Standard Time" },
	{ "America/St_Lucia", "SA Western Standard Time" },
	{ "America/St_Thomas", "SA Western Standard Time" },
	{ "America/St_Vincent", "SA Western Standard Time" },
	{ "America/Swift_Current", "Canada Central Standard Time" },
	{ "America/Tegucigalpa", "Central America Standard Time" },
	{ "America/Thule", "Atlantic Standard Time" },
	{ "America/Thunder_Bay", "Eastern Standard Time" },
	{ "America/Tijuana", "Pacific Standard Time (Mexico)" },
	{ "America/Toronto", "Eastern Standard Time" },
	{ "America/Tortola", "SA Western Standard Time" },
	{ "America/Vancouver", "Pacific Standard Time" },
	{ "America/Whitehorse", "Pacific Standard Time" },
	{ "America/Winnipeg", "Central Standard Time" },
	{ "America/Yakutat", "Alaskan Standard Time" },
	{ "America/Yellowknife", "Mountain Standard Time" },
	{ "Antarctica/Casey", "Singapore Standard Time" },
	{ "Antarctica/Davis", "SE Asia Standard Time" },
	{ "Antarctica/DumontDUrville", "West Pacific Standard Time" },
	{ "Antarctica/Macquarie", "Central Pacific Standard Time" },
	{ "Antarctica/Mawson", "West Asia Standard Time" },
	{ "Antarctica/McMurdo", "New Zealand Standard Time" },
	{ "Antarctica/Palmer", "SA Eastern Standard Time" },
	{ "Antarctica/Rothera", "SA Eastern Standard Time" },
	{ "Antarctica/Syowa", "E. Africa Standard Time" },
	{ "Antarctica/Vostok", "Central Asia Standard Time" },
	{ "Arctic/Longyearbyen", "W. Europe Standard Time" },
	{ "Asia/Aden", "Arab Standard Time" },
	{ "Asia/Almaty", "Central Asia Standard Time" },
	{ "Asia/Amman", "Jordan Standard Time" },
	{ "Asia/Anadyr", "Russia Time Zone 11" },
	{ "Asia/Aqtau", "West Asia Standard Time" },
	{ "Asia/Aqtobe", "West Asia Standard Time" },
	{ "Asia/Ashgabat", "West Asia Standard Time" },
	{ "Asia/Atyrau", "West Asia Standard Time" },
	{ "Asia/Baghdad", "Arabic Standard Time" },
	{ "Asia/Bahrain", "Arab Standard Time" },
	{ "Asia/Baku", "Azerbaijan Standard Time" },
	{ "Asia/Bangkok", "SE Asia Standard Time" },
	{ "Asia/Barnaul", "Altai Standard Time" },
	{ "Asia/Beirut", "Middle East Standard Time" },
	{ "Asia/Bishkek", "Central Asia Standard Time" },
	{ "Asia/Brunei", "Singapore Standard Time" },
	{ "Asia/Calcutta", "India Standard Time" },
	{ "Asia/Chita", "Transbaikal Standard Time" },
	{ "Asia/Choibalsan", "Ulaanbaatar Standard Time" },
	{ "Asia/Colombo", "Sri Lanka Standard Time" },
	{ "Asia/Damascus", "Syria Standard Time" },
	{ "Asia/Dhaka", "Bangladesh Standard Time" },
	{ "Asia/Dili", "Tokyo Standard Time" },
	{ "Asia/Dubai", "Arabian Standard Time" },
	{ "Asia/Dushanbe", "West Asia Standard Time" },
	{ "Asia/Famagusta", "GTB Standard Time" },
	{ "Asia/Gaza", "West Bank Standard Time" },
	{ "Asia/Hebron", "West Bank Standard Time" },
	{ "Asia/Hong_Kong", "China Standard Time" },
	{ "Asia/Hovd", "W. Mongolia Standard Time" },
	{ "Asia/Irkutsk", "North Asia East Standard Time" },
	{ "Asia/Jakarta", "SE Asia Standard Time" },
	{ "Asia/Jayapura", "Tokyo Standard Time" },
	{ "Asia/Jerusalem", "Israel Standard Time" },
	{ "Asia/Kabul", "Afghanistan Standard Time" },
	{ "Asia/Kamchatka", "Russia Time Zone 11" },
	{ "Asia/Karachi", "Pakistan Standard Time" },
	{ "Asia/Katmandu", "Nepal Standard Time" },
	{ "Asia/Khandyga", "Yakutsk Standard Time" },
	{ "Asia/Krasnoyarsk", "North Asia Standard Time" },
	{ "Asia/Kuala_Lumpur", "Singapore Standard Time" },
	{ "Asia/Kuching", "Singapore Standard Time" },
	{ "Asia/Kuwait", "Arab Standard Time" },
	{ "Asia/Macau", "China Standard Time" },
	{ "Asia/Magadan", "Magadan Standard Time" },
	{ "Asia/Makassar", "Singapore Standard Time" },
	{ "Asia/Manila", "Singapore Standard Time" },
	{ "Asia/Muscat", "Arabian Standard Time" },
	{ "Asia/Nicosia", "GTB Standard Time" },
	{ "Asia/Novokuznetsk", "North Asia Standard Time" },
	{ "Asia/Novosibirsk", "N. Central Asia Standard Time" },
	{ "Asia/Omsk", "Omsk Standard Time" },
	{ "Asia/Oral", "West Asia Standard Time" },
	{ "Asia/Phnom_Penh", "SE Asia Standard Time" },
	{ "Asia/Pontianak", "SE Asia Standard Time" },
	{ "Asia/Pyongyang", "North Korea Standard Time" },
	{ "Asia/Qatar", "Arab Standard Time" },
	{ "Asia/Qostanay", "Central Asia Standard Time" },
	{ "Asia/Qyzylorda", "Qyzylorda Standard Time" },
	{ "Asia/Rangoon", "Myanmar Standard Time" },
	{ "Asia/Riyadh", "Arab Standard Time" },
	{ "Asia/Saigon", "SE Asia Standard Time" },
	{ "Asia/Sakhalin", "Sakhalin Standard Time" },
	{ "Asia/Samarkand", "West Asia Standard Time" },
	{ "Asia/Seoul", "Korea Standard Time" },
	{ "Asia/Shanghai", "China Standard Time" },
	{ "Asia/Singapore", "Singapore Standard Time" },
	{ "Asia/Srednekolymsk", "Russia Time Zone 10" },
	{ "Asia/Taipei", "Taipei Standard Time" },
	{ "Asia/Tashkent", "West Asia Standard Time" },
	{ "Asia/Tbilisi", "Georgian Standard Time" },
	{ "Asia/Tehran", "Iran Standard Time" },
	{ "Asia/Thimphu", "Bangladesh Standard Time" },
	{ "Asia/Tokyo", "Tokyo Standard Time" },
	{ "Asia/Tomsk", "Tomsk Standard Time" },
	{ "Asia/Ulaanbaatar", "Ulaanbaatar Standard Time" },
	{ "Asia/Urumqi", "Central Asia Standard Time" },
	{ "Asia/Ust-Nera", "Vladivostok Standard Time" },
	{ "Asia/Vientiane", "SE Asia Standard Time" },
	{ "Asia/Vladivostok", "Vladivostok Standard Time" },
	{ "Asia/Yakutsk", "Yakutsk Standard Time" },
	{ "Asia/Yekaterinburg", "Ekaterinburg Standard Time" },
	{ "Asia/Yerevan", "Caucasus Standard Time" },
	{ "Atlantic/Azores", "Azores Standard Time" },
	{ "Atlantic/Bermuda", "Atlantic Standard Time" },
	{ "Atlantic/Canary", "GMT Standard Time" },
	{ "Atlantic/Cape_Verde", "Cape Verde Standard Time" },
	{ "Atlantic/Faeroe", "GMT Standard Time" },
	{ "Atlantic/Madeira", "GMT Standard Time" },
	{ "Atlantic/Reykjavik", "Greenwich Standard Time" },
	{ "Atlantic/South_Georgia", "UTC-02" },
	{ "Atlantic/St_Helena", "Greenwich Standard Time" },
	{ "Atlantic/Stanley", "SA Eastern Standard Time" },
	{ "Australia/Adelaide", "Cen. Australia Standard Time" },
	{ "Australia/Brisbane", "E. Australia Standard Time" },
	{ "Australia/Broken_Hill", "Cen. Australia Standard Time" },
	{ "Australia/Currie", "Tasmania Standard Time" },
	{ "Australia/Darwin", "AUS Central Standard Time" },
	{ "Australia/Eucla", "Aus Central W. Standard Time" },
	{ "Australia/Hobart", "Tasmania Standard Time" },
	{ "Australia/Lindeman", "E. Australia Standard Time" },
	{ "Australia/Lord_Howe", "Lord Howe Standard Time" },
	{ "Australia/Melbourne", "AUS Eastern Standard Time" },
	{ "Australia/Perth", "W. Australia Standard Time" },
	{ "Australia/Sydney", "AUS Eastern Standard Time" },
	{ "CST6CDT", "Central Standard Time" },
	{ "EST5EDT", "Eastern Standard Time" },
	{ "Etc/GMT", "UTC" },
	{ "Etc/GMT+1", "Cape Verde Standard Time" },
	{ "Etc/GMT+10", "Hawaiian Standard Time" },
	{ "Etc/GMT+11", "UTC-11" },
	{ "Etc/GMT+12", "Dateline Standard Time" },
	{ "Etc/GMT+2", "UTC-02" },
	{ "Etc/GMT+3", "SA Eastern Standard Time" },
	{ "Etc/GMT+4", "SA Western Standard Time" },
	{ "Etc/GMT+5", "SA Pacific Standard Time" },
	{ "Etc/GMT+6", "Central America Standard Time" },
	{ "Etc/GMT+7", "US Mountain Standard Time" },
	{ "Etc/GMT+8", "UTC-08" },
	{ "Etc/GMT+9", "UTC-09" },
	{ "Etc/GMT-1", "W. Central Africa Standard Time" },
	{ "Etc/GMT-10", "West Pacific Standard Time" },
	{ "Etc/GMT-11", "Central Pacific Standard Time" },
	{ "Etc/GMT-12", "UTC+12" },
	{ "Etc/GMT-13", "UTC+13" },
	{ "Etc/GMT-14", "Line Islands Standard Time" },
	{ "Etc/GMT-2", "South Africa Standard Time" },
	{ "Etc/GMT-3", "E. Africa Standard Time" },
	{ "Etc/GMT-4", "Arabian Standard Time" },
	{ "Etc/GMT-5", "West Asia Standard Time" },
	{ "Etc/GMT-6", "Central Asia Standard Time" },
	{ "Etc/GMT-7", "SE Asia Standard Time" },
	{ "Etc/GMT-8", "Singapore Standard Time" },
	{ "Etc/GMT-9", "Tokyo Standard Time" },
	{ "Etc/UTC", "UTC" },
	{ "Europe/Amsterdam", "W. Europe Standard Time" },
	{ "Europe/Andorra", "W. Europe Standard Time" },
	{ "Europe/Astrakhan", "Astrakhan Standard Time" },
	{ "Europe/Athens", "GTB Standard Time" },
	{ "Europe/Belgrade", "Central Europe Standard Time" },
	{ "Europe/Berlin", "W. Europe Standard Time" },
	{ "Europe/Bratislava", "Central Europe Standard Time" },
	{ "Europe/Brussels", "Romance Standard Time" },
	{ "Europe/Bucharest", "GTB Standard Time" },
	{ "Europe/Budapest", "Central Europe Standard Time" },
	{ "Europe/Busingen", "W. Europe Standard Time" },
	{ "Europe/Chisinau", "E. Europe Standard Time" },
	{ "Europe/Copenhagen", "Romance Standard Time" },
	{ "Europe/Dublin", "GMT Standard Time" },
	{ "Europe/Gibraltar", "W. Europe Standard Time" },
	{ "Europe/Guernsey", "GMT Standard Time" },
	{ "Europe/Helsinki", "FLE Standard Time" },
	{ "Europe/Isle_of_Man", "GMT Standard Time" },
	{ "Europe/Istanbul", "Turkey Standard Time" },
	{ "Europe/Jersey", "GMT Standard Time" },
	{ "Europe/Kaliningrad", "Kaliningrad Standard Time" },
	{ "Europe/Kiev", "FLE Standard Time" },
	{ "Europe/Kirov", "Russian Standard Time" },
	{ "Europe/Lisbon", "GMT Standard Time" },
	{ "Europe/Ljubljana", "Central Europe Standard Time" },
	{ "Europe/London", "GMT Standard Time" },
	{ "Europe/Luxembourg", "W. Europe Standard Time" },
	{ "Europe/Madrid", "Romance Standard Time" },
	{ "Europe/Malta", "W. Europe Standard Time" },
	{ "Europe/Mariehamn", "FLE Standard Time" },
	{ "Europe/Minsk", "Belarus Standard Time" },
	{ "Europe/Monaco", "W. Europe Standard Time" },
	{ "Europe/Moscow", "Russian Standard Time" },
	{ "Europe/Oslo", "W. Europe Standard Time" },
	{ "Europe/Paris", "Romance Standard Time" },
	{ "Europe/Podgorica", "Central Europe Standard Time" },
	{ "Europe/Prague", "Central Europe Standard Time" },
	{ "Europe/Riga", "FLE Standard Time" },
	{ "Europe/Rome", "W. Europe Standard Time" },
	{ "Europe/Samara", "Russia Time Zone 3" },
	{ "Europe/San_Marino", "W. Europe Standard Time" },
	{ "Europe/Sarajevo", "Central European Standard Time" },
	{ "Europe/Saratov", "Saratov Standard Time" },
	{ "Europe/Simferopol", "Russian Standard Time" },
	{ "Europe/Skopje", "Central European Standard Time" },
	{ "Europe/Sofia", "FLE Standard Time" },
	{ "Europe/Stockholm", "W. Europe Standard Time" },
	{ "Europe/Tallinn", "FLE Standard Time" },
	{ "Europe/Tirane", "Central Europe Standard Time" },
	{ "Europe/Ulyanovsk", "Astrakhan Standard Time" },
	{ "Europe/Uzhgorod", "FLE Standard Time" },
	{ "Europe/Vaduz", "W. Europe Standard Time" },
	{ "Europe/Vatican", "W. Europe Standard Time" },
	{ "Europe/Vienna", "W. Europe Standard Time" },
	{ "Europe/Vilnius", "FLE Standard Time" },
	{ "Europe/Volgograd", "Volgograd Standard Time" },
	{ "Europe/Warsaw", "Central European Standard Time" },
	{ "Europe/Zagreb", "Central European Standard Time" },
	{ "Europe/Zaporozhye", "FLE Standard Time" },
	{ "Europe/Zurich", "W. Europe Standard Time" },
	{ "Indian/Antananarivo", "E. Africa Standard Time" },
	{ "Indian/Chagos", "Central Asia Standard Time" },
	{ "Indian/Christmas", "SE Asia Standard Time" },
	{ "Indian/Cocos", "Myanmar Standard Time" },
	{ "Indian/Comoro", "E. Africa Standard Time" },
	{ "Indian/Kerguelen", "West Asia Standard Time" },
	{ "Indian/Mahe", "Mauritius Standard Time" },
	{ "Indian/Maldives", "West Asia Standard Time" },
	{ "Indian/Mauritius", "Mauritius Standard Time" },
	{ "Indian/Mayotte", "E. Africa Standard Time" },
	{ "Indian/Reunion", "Mauritius Standard Time" },
	{ "MST7MDT", "Mountain Standard Time" },
	{ "PST8PDT", "Pacific Standard Time" },
	{ "Pacific/Apia", "Samoa Standard Time" },
	{ "Pacific/Auckland", "New Zealand Standard Time" },
	{ "Pacific/Bougainville", "Bougainville Standard Time" },
	{ "Pacific/Chatham", "Chatham Islands Standard Time" },
	{ "Pacific/Easter", "Easter Island Standard Time" },
	{ "Pacific/Efate", "Central Pacific Standard Time" },
	{ "Pacific/Enderbury", "UTC+13" },
	{ "Pacific/Fakaofo", "UTC+13" },
	{ "Pacific/Fiji", "Fiji Standard Time" },
	{ "Pacific/Funafuti", "UTC+12" },
	{ "Pacific/Galapagos", "Central America Standard Time" },
	{ "Pacific/Gambier", "UTC-09" },
	{ "Pacific/Guadalcanal", "Central Pacific Standard Time" },
	{ "Pacific/Guam", "West Pacific Standard Time" },
	{ "Pacific/Honolulu", "Hawaiian Standard Time" },
	{ "Pacific/Johnston", "Hawaiian Standard Time" },
	{ "Pacific/Kiritimati", "Line Islands Standard Time" },
	{ "Pacific/Kosrae", "Central Pacific Standard Time" },
	{ "Pacific/Kwajalein", "UTC+12" },
	{ "Pacific/Majuro", "UTC+12" },
	{ "Pacific/Marquesas", "Marquesas Standard Time" },
	{ "Pacific/Midway", "UTC-11" },
	{ "Pacific/Nauru", "UTC+12" },
	{ "Pacific/Niue", "UTC-11" },
	{ "Pacific/Norfolk", "Norfolk Standard Time" },
	{ "Pacific/Noumea", "Central Pacific Standard Time" },
	{ "Pacific/Pago_Pago", "UTC-11" },
	{ "Pacific/Palau", "Tokyo Standard Time" },
	{ "Pacific/Pitcairn", "UTC-08" },
	{ "Pacific/Ponape", "Central Pacific Standard Time" },
	{ "Pacific/Port_Moresby", "West Pacific Standard Time" },
	{ "Pacific/Rarotonga", "Hawaiian Standard Time" },
	{ "Pacific/Saipan", "West Pacific Standard Time" },
	{ "Pacific/Tahiti", "Hawaiian Standard Time" },
	{ "Pacific/Tarawa", "UTC+12" },
	{ "Pacific/Tongatapu", "Tonga Standard Time" },
	{ "Pacific/Truk", "West Pacific Standard Time" },
	{ "Pacific/Wake", "UTC+12" },
	{ "Pacific/Wallis", "UTC+12" },
};
static const std::unordered_map<std::string, std::string> windows_to_standard = {
	{ "AUS Central Standard Time", "Australia/Darwin" },
	{ "AUS Eastern Standard Time", "Australia/Sydney" },
	{ "Afghanistan Standard Time", "Asia/Kabul" },
	{ "Alaskan Standard Time", "America/Anchorage" },
	{ "Aleutian Standard Time", "America/Adak" },
	{ "Altai Standard Time", "Asia/Barnaul" },
	{ "Arab Standard Time", "Asia/Riyadh" },
	{ "Arabian Standard Time", "Asia/Dubai" },
	{ "Arabic Standard Time", "Asia/Baghdad" },
	{ "Argentina Standard Time", "America/Buenos_Aires" },
	{ "Astrakhan Standard Time", "Europe/Astrakhan" },
	{ "Atlantic Standard Time", "America/Halifax" },
	{ "Aus Central W. Standard Time", "Australia/Eucla" },
	{ "Azerbaijan Standard Time", "Asia/Baku" },
	{ "Azores Standard Time", "Atlantic/Azores" },
	{ "Bahia Standard Time", "America/Bahia" },
	{ "Bangladesh Standard Time", "Asia/Dhaka" },
	{ "Belarus Standard Time", "Europe/Minsk" },
	{ "Bougainville Standard Time", "Pacific/Bougainville" },
	{ "Canada Central Standard Time", "America/Regina" },
	{ "Cape Verde Standard Time", "Atlantic/Cape_Verde" },
	{ "Caucasus Standard Time", "Asia/Yerevan" },
	{ "Cen. Australia Standard Time", "Australia/Adelaide" },
	{ "Central America Standard Time", "America/Guatemala" },
	{ "Central Asia Standard Time", "Asia/Almaty" },
	{ "Central Brazilian Standard Time", "America/Cuiaba" },
	{ "Central Europe Standard Time", "Europe/Budapest" },
	{ "Central European Standard Time", "Europe/Warsaw" },
	{ "Central Pacific Standard Time", "Pacific/Guadalcanal" },
	{ "Central Standard Time", "America/Chicago" },
	{ "Central Standard Time (Mexico)", "America/Mexico_City" },
	{ "Chatham Islands Standard Time", "Pacific/Chatham" },
	{ "China Standard Time", "Asia/Shanghai" },
	{ "Cuba Standard Time", "America/Havana" },
	{ "Dateline Standard Time", "Etc/GMT+12" },
	{ "E. Africa Standard Time", "Africa/Nairobi" },
	{ "E. Australia Standard Time", "Australia/Brisbane" },
	{ "E. Europe Standard Time", "Europe/Chisinau" },
	{ "E. South America Standard Time", "America/Sao_Paulo" },
	{ "Easter Island Standard Time", "Pacific/Easter" },
	{ "Eastern Standard Time", "America/New_York" },
	{ "Eastern Standard Time (Mexico)", "America/Cancun" },
	{ "Egypt Standard Time", "Africa/Cairo" },
	{ "Ekaterinburg Standard Time", "Asia/Yekaterinburg" },
	{ "FLE Standard Time", "Europe/Kiev" },
	{ "Fiji Standard Time", "Pacific/Fiji" },
	{ "GMT Standard Time", "Europe/London" },
	{ "GTB Standard Time", "Europe/Bucharest" },
	{ "Georgian Standard Time", "Asia/Tbilisi" },
	{ "Greenland Standard Time", "America/Godthab" },
	{ "Greenwich Standard Time", "Atlantic/Reykjavik" },
	{ "Haiti Standard Time", "America/Port-au-Prince" },
	{ "Hawaiian Standard Time", "Pacific/Honolulu" },
	{ "India Standard Time", "Asia/Calcutta" },
	{ "Iran Standard Time", "Asia/Tehran" },
	{ "Israel Standard Time", "Asia/Jerusalem" },
	{ "Jordan Standard Time", "Asia/Amman" },
	{ "Kaliningrad Standard Time", "Europe/Kaliningrad" },
	{ "Korea Standard Time", "Asia/Seoul" },
	{ "Libya Standard Time", "Africa/Tripoli" },
	{ "Line Islands Standard Time", "Pacific/Kiritimati" },
	{ "Lord Howe Standard Time", "Australia/Lord_Howe" },
	{ "Magadan Standard Time", "Asia/Magadan" },
	{ "Magallanes Standard Time", "America/Punta_Arenas" },
	{ "Marquesas Standard Time", "Pacific/Marquesas" },
	{ "Mauritius Standard Time", "Indian/Mauritius" },
	{ "Middle East Standard Time", "Asia/Beirut" },
	{ "Montevideo Standard Time", "America/Montevideo" },
	{ "Morocco Standard Time", "Africa/Casablanca" },
	{ "Mountain Standard Time", "America/Denver" },
	{ "Mountain Standard Time (Mexico)", "America/Chihuahua" },
	{ "Myanmar Standard Time", "Asia/Rangoon" },
	{ "N. Central Asia Standard Time", "Asia/Novosibirsk" },
	{ "Namibia Standard Time", "Africa/Windhoek" },
	{ "Nepal Standard Time", "Asia/Katmandu" },
	{ "New Zealand Standard Time", "Pacific/Auckland" },
	{ "Newfoundland Standard Time", "America/St_Johns" },
	{ "Norfolk Standard Time", "Pacific/Norfolk" },
	{ "North Asia East Standard Time", "Asia/Irkutsk" },
	{ "North Asia Standard Time", "Asia/Krasnoyarsk" },
	{ "North Korea Standard Time", "Asia/Pyongyang" },
	{ "Omsk Standard Time", "Asia/Omsk" },
	{ "Pacific SA Standard Time", "America/Santiago" },
	{ "Pacific Standard Time", "America/Los_Angeles" },
	{ "Pacific Standard Time (Mexico)", "America/Tijuana" },
	{ "Pakistan Standard Time", "Asia/Karachi" },
	{ "Paraguay Standard Time", "America/Asuncion" },
	{ "Qyzylorda Standard Time", "Asia/Qyzylorda" },
	{ "Romance Standard Time", "Europe/Paris" },
	{ "Russia Time Zone 10", "Asia/Srednekolymsk" },
	{ "Russia Time Zone 11", "Asia/Kamchatka" },
	{ "Russia Time Zone 3", "Europe/Samara" },
	{ "Russian Standard Time", "Europe/Moscow" },
	{ "SA Eastern Standard Time", "America/Cayenne" },
	{ "SA Pacific Standard Time", "America/Bogota" },
	{ "SA Western Standard Time", "America/La_Paz" },
	{ "SE Asia Standard Time", "Asia/Bangkok" },
	{ "Saint Pierre Standard Time", "America/Miquelon" },
	{ "Sakhalin Standard Time", "Asia/Sakhalin" },
	{ "Samoa Standard Time", "Pacific/Apia" },
	{ "Sao Tome Standard Time", "Africa/Sao_Tome" },
	{ "Saratov Standard Time", "Europe/Saratov" },
	{ "Singapore Standard Time", "Asia/Singapore" },
	{ "South Africa Standard Time", "Africa/Johannesburg" },
	{ "Sri Lanka Standard Time", "Asia/Colombo" },
	{ "Sudan Standard Time", "Africa/Khartoum" },
	{ "Syria Standard Time", "Asia/Damascus" },
	{ "Taipei Standard Time", "Asia/Taipei" },
	{ "Tasmania Standard Time", "Australia/Hobart" },
	{ "Tocantins Standard Time", "America/Araguaina" },
	{ "Tokyo Standard Time", "Asia/Tokyo" },
	{ "Tomsk Standard Time", "Asia/Tomsk" },
	{ "Tonga Standard Time", "Pacific/Tongatapu" },
	{ "Transbaikal Standard Time", "Asia/Chita" },
	{ "Turkey Standard Time", "Europe/Istanbul" },
	{ "Turks And Caicos Standard Time", "America/Grand_Turk" },
	{ "US Eastern Standard Time", "America/Indianapolis" },
	{ "US Mountain Standard Time", "America/Phoenix" },
	{ "UTC", "Etc/GMT" },
	{ "UTC+12", "Etc/GMT-12" },
	{ "UTC+13", "Etc/GMT-13" },
	{ "UTC-02", "Etc/GMT+2" },
	{ "UTC-08", "Etc/GMT+8" },
	{ "UTC-09", "Etc/GMT+9" },
	{ "UTC-11", "Etc/GMT+11" },
	{ "Ulaanbaatar Standard Time", "Asia/Ulaanbaatar" },
	{ "Venezuela Standard Time", "America/Caracas" },
	{ "Vladivostok Standard Time", "Asia/Vladivostok" },
	{ "Volgograd Standard Time", "Europe/Volgograd" },
	{ "W. Australia Standard Time", "Australia/Perth" },
	{ "W. Central Africa Standard Time", "Africa/Lagos" },
	{ "W. Europe Standard Time", "Europe/Berlin" },
	{ "W. Mongolia Standard Time", "Asia/Hovd" },
	{ "West Asia Standard Time", "Asia/Tashkent" },
	{ "West Bank Standard Time", "Asia/Hebron" },
	{ "West Pacific Standard Time", "Pacific/Port_Moresby" },
	{ "Yakutsk Standard Time", "Asia/Yakutsk" },
};
static const std::unordered_map<std::string, size_t> zone_ids = {
	{ "Africa/Abidjan", 197 },
	{ "Africa/Accra", 198 },
	{ "Africa/Addis_Ababa", 311 },
	{ "Africa/Algiers", 252 },
	{ "Africa/Asmera", 310 },
	{ "Africa/Bamako", 203 },
	{ "Africa/Bangui", 249 },
	{ "Africa/Banjul", 199 },
	{ "Africa/Bissau", 201 },
	{ "Africa/Blantyre", 275 },
	{ "Africa/Brazzaville", 250 },
	{ "Africa/Bujumbura", 271 },
	{ "Africa/Cairo", 265 },
	{ "Africa/Casablanca", 210 },
	{ "Africa/Ceuta", 240 },
	{ "Africa/Conakry", 200 },
	{ "Africa/Dakar", 207 },
	{ "Africa/Dar_es_Salaam", 316 },
	{ "Africa/Djibouti", 309 },
	{ "Africa/Douala", 251 },
	{ "Africa/El_Aaiun", 211 },
	{ "Africa/Freetown", 206 },
	{ "Africa/Gaborone", 272 },
	{ "Africa/Harare", 280 },
	{ "Africa/Johannesburg", 270 },
	{ "Africa/Juba", 315 },
	{ "Africa/Kampala", 317 },
	{ "Africa/Khartoum", 293 },
	{ "Africa/Kigali", 277 },
	{ "Africa/Kinshasa", 248 },
	{ "Africa/Lagos", 245 },
	{ "Africa/Libreville", 253 },
	{ "Africa/Lome", 208 },
	{ "Africa/Luanda", 246 },
	{ "Africa/Lubumbashi", 273 },
	{ "Africa/Lusaka", 279 },
	{ "Africa/Malabo", 254 },
	{ "Africa/Maputo", 276 },
	{ "Africa/Maseru", 274 },
	{ "Africa/Mbabane", 278 },
	{ "Africa/Mogadishu", 314 },
	{ "Africa/Monrovia", 202 },
	{ "Africa/Nairobi", 307 },
	{ "Africa/Ndjamena", 256 },
	{ "Africa/Niamey", 255 },
	{ "Africa/Nouakchott", 204 },
	{ "Africa/Ouagadougou", 196 },
	{ "Africa/Porto-Novo", 247 },
	{ "Africa/Sao_Tome", 209 },
	{ "Africa/Tripoli", 294 },
	{ "Africa/Tunis", 257 },
	{ "Africa/Windhoek", 295 },
	{ "America/Adak", 5 },
	{ "America/Anchorage", 12 },
	{ "America/Anguilla", 117 },
	{ "America/Antigua", 116 },
	{ "America/Araguaina", 146 },
	{ "America/Argentina/La_Rioja", 160 },
	{ "America/Argentina/Rio_Gallegos", 161 },
	{ "America/Argentina/Salta", 162 },
	{ "America/Argentina/San_Juan", 163 },
	{ "America/Argentina/San_Luis", 164 },
	{ "America/Argentina/Tucuman", 165 },
	{ "America/Argentina/Ushuaia", 166 },
	{ "America/Aruba", 118 },
	{ "America/Asuncion", 105 },
	{ "America/Bahia", 175 },
	{ "America/Bahia_Banderas", 68 },
	{ "America/Barbados", 119 },
	{ "America/Belem", 152 },
	{ "America/Belize", 46 },
	{ "America/Blanc-Sablon", 125 },
	{ "America/Boa_Vista", 123 },
	{ "America/Bogota", 73 },
	{ "America/Boise", 43 },
	{ "America/Buenos_Aires", 159 },
	{ "America/Cambridge_Bay", 39 },
	{ "America/Campo_Grande", 114 },
	{ "America/Cancun", 83 },
	{ "America/Caracas", 112 },
	{ "America/Catamarca", 167 },
	{ "America/Cayenne", 148 },
	{ "America/Cayman", 79 },
	{ "America/Chicago", 53 },
	{ "America/Chihuahua", 35 },
	{ "America/Coral_Harbour", 76 },
	{ "America/Cordoba", 168 },
	{ "America/Costa_Rica", 47 },
	{ "America/Creston", 31 },
	{ "America/Cuiaba", 113 },
	{ "America/Curacao", 126 },
	{ "America/Danmarkshavn", 184 },
	{ "America/Dawson", 26 },
	{ "America/Dawson_Creek", 30 },
	{ "America/Denver", 37 },
	{ "America/Detroit", 92 },
	{ "America/Dominica", 127 },
	{ "America/Edmonton", 38 },
	{ "America/Eirunepe", 75 },
	{ "America/El_Salvador", 51 },
	{ "America/Fortaleza", 151 },
	{ "America/Fort_Nelson", 32 },
	{ "America/Glace_Bay", 108 },
	{ "America/Godthab", 171 },
	{ "America/Goose_Bay", 109 },
	{ "America/Grand_Turk", 104 },
	{ "America/Grenada", 129 },
	{ "America/Guadeloupe", 130 },
	{ "America/Guatemala", 45 },
	{ "America/Guayaquil", 77 },
	{ "America/Guyana", 131 },
	{ "America/Halifax", 106 },
	{ "America/Havana", 100 },
	{ "America/Hermosillo", 33 },
	{ "America/Indiana/Knox", 59 },
	{ "America/Indiana/Marengo", 102 },
	{ "America/Indiana/Petersburg", 93 },
	{ "America/Indianapolis", 101 },
	{ "America/Indiana/Tell_City", 60 },
	{ "America/Indiana/Vevay", 103 },
	{ "America/Indiana/Vincennes", 94 },
	{ "America/Indiana/Winamac", 95 },
	{ "America/Inuvik", 40 },
	{ "America/Iqaluit", 87 },
	{ "America/Jamaica", 78 },
	{ "America/Jujuy", 169 },
	{ "America/Juneau", 13 },
	{ "America/Kentucky/Monticello", 96 },
	{ "America/Kralendijk", 121 },
	{ "America/La_Paz", 115 },
	{ "America/Lima", 81 },
	{ "America/Los_Angeles", 24 },
	{ "America/Louisville", 97 },
	{ "America/Lower_Princes", 138 },
	{ "America/Maceio", 153 },
	{ "America/Managua", 50 },
	{ "America/Manaus", 122 },
	{ "America/Marigot", 134 },
	{ "America/Martinique", 135 },
	{ "America/Matamoros", 58 },
	{ "America/Mazatlan", 36 },
	{ "America/Mendoza", 170 },
	{ "America/Menominee", 61 },
	{ "America/Merida", 69 },
	{ "America/Metlakatla", 14 },
	{ "America/Mexico_City", 67 },
	{ "America/Miquelon", 174 },
	{ "America/Moncton", 110 },
	{ "America/Monterrey", 70 },
	{ "America/Montevideo", 172 },
	{ "America/Montreal", 88 },
	{ "America/Montserrat", 136 },
	{ "America/Nassau", 85 },
	{ "America/New_York", 84 },
	{ "America/Nipigon", 89 },
	{ "America/Nome", 15 },
	{ "America/Noronha", 177 },
	{ "America/North_Dakota/Beulah", 62 },
	{ "America/North_Dakota/Center", 63 },
	{ "America/North_Dakota/New_Salem", 64 },
	{ "America/Ojinaga", 42 },
	{ "America/Panama", 80 },
	{ "America/Pangnirtung", 90 },
	{ "America/Paramaribo", 157 },
	{ "America/Phoenix", 29 },
	{ "America/Port-au-Prince", 99 },
	{ "America/Port_of_Spain", 139 },
	{ "America/Porto_Velho", 124 },
	{ "America/Puerto_Rico", 137 },
	{ "America/Punta_Arenas", 173 },
	{ "America/Rainy_River", 55 },
	{ "America/Rankin_Inlet", 56 },
	{ "America/Recife", 154 },
	{ "America/Regina", 71 },
	{ "America/Resolute", 57 },
	{ "America/Rio_Branco", 74 },
	{ "America/Santa_Isabel", 21 },
	{ "America/Santarem", 155 },
	{ "America/Santiago", 144 },
	{ "America/Santo_Domingo", 128 },
	{ "America/Sao_Paulo", 147 },
	{ "America/Scoresbysund", 180 },
	{ "America/Sitka", 16 },
	{ "America/St_Barthelemy", 120 },
	{ "America/St_Johns", 145 },
	{ "America/St_Kitts", 132 },
	{ "America/St_Lucia", 133 },
	{ "America/St_Thomas", 142 },
	{ "America/St_Vincent", 140 },
	{ "America/Swift_Current", 72 },
	{ "America/Tegucigalpa", 49 },
	{ "America/Thule", 111 },
	{ "America/Thunder_Bay", 91 },
	{ "America/Tijuana", 20 },
	{ "America/Toronto", 86 },
	{ "America/Tortola", 141 },
	{ "America/Vancouver", 25 },
	{ "America/Whitehorse", 27 },
	{ "America/Winnipeg", 54 },
	{ "America/Yakutat", 17 },
	{ "America/Yellowknife", 41 },
	{ "Antarctica/Casey", 386 },
	{ "Antarctica/Davis", 367 },
	{ "Antarctica/DumontDUrville", 416 },
	{ "Antarctica/Macquarie", 432 },
	{ "Antarctica/Mawson", 337 },
	{ "Antarctica/McMurdo", 441 },
	{ "Antarctica/Palmer", 150 },
	{ "Antarctica/Rothera", 149 },
	{ "Antarctica/Syowa", 308 },
	{ "Antarctica/Vostok", 355 },
	{ "Arctic/Longyearbyen", 226 },
	{ "Asia/Aden", 302 },
	{ "Asia/Almaty", 354 },
	{ "Asia/Amman", 259 },
	{ "Asia/Anadyr", 439 },
	{ "Asia/Aqtau", 339 },
	{ "Asia/Aqtobe", 340 },
	{ "Asia/Ashgabat", 345 },
	{ "Asia/Atyrau", 341 },
	{ "Asia/Baghdad", 296 },
	{ "Asia/Bahrain", 299 },
	{ "Asia/Baku", 326 },
	{ "Asia/Bangkok", 366 },
	{ "Asia/Barnaul", 375 },
	{ "Asia/Beirut", 264 },
	{ "Asia/Bishkek", 358 },
	{ "Asia/Brunei", 387 },
	{ "Asia/Calcutta", 351 },
	{ "Asia/Chita", 398 },
	{ "Asia/Choibalsan", 396 },
	{ "Asia/Colombo", 352 },
	{ "Asia/Damascus", 267 },
	{ "Asia/Dhaka", 361 },
	{ "Asia/Dili", 402 },
	{ "Asia/Dubai", 321 },
	{ "Asia/Dushanbe", 344 },
	{ "Asia/Famagusta", 262 },
	{ "Asia/Gaza", 269 },
	{ "Asia/Hebron", 268 },
	{ "Asia/Hong_Kong", 382 },
	{ "Asia/Hovd", 376 },
	{ "Asia/Irkutsk", 384 },
	{ "Asia/Jakarta", 369 },
	{ "Asia/Jayapura", 400 },
	{ "Asia/Jerusalem", 291 },
	{ "Asia/Kabul", 335 },
	{ "Asia/Kamchatka", 438 },
	{ "Asia/Karachi", 349 },
	{ "Asia/Katmandu", 353 },
	{ "Asia/Khandyga", 407 },
	{ "Asia/Krasnoyarsk", 377 },
	{ "Asia/Kuala_Lumpur", 389 },
	{ "Asia/Kuching", 390 },
	{ "Asia/Kuwait", 300 },
	{ "Asia/Macau", 383 },
	{ "Asia/Magadan", 428 },
	{ "Asia/Makassar", 388 },
	{ "Asia/Manila", 391 },
	{ "Asia/Muscat", 322 },
	{ "Asia/Nicosia", 261 },
	{ "Asia/Novokuznetsk", 378 },
	{ "Asia/Novosibirsk", 379 },
	{ "Asia/Omsk", 363 },
	{ "Asia/Oral", 338 },
	{ "Asia/Phnom_Penh", 371 },
	{ "Asia/Pontianak", 370 },
	{ "Asia/Pyongyang", 404 },
	{ "Asia/Qatar", 301 },
	{ "Asia/Qostanay", 359 },
	{ "Asia/Qyzylorda", 350 },
	{ "Asia/Rangoon", 364 },
	{ "Asia/Riyadh", 298 },
	{ "Asia/Saigon", 373 },
	{ "Asia/Sakhalin", 430 },
	{ "Asia/Samarkand", 346 },
	{ "Asia/Seoul", 405 },
	{ "Asia/Shanghai", 381 },
	{ "Asia/Singapore", 385 },
	{ "Asia/Srednekolymsk", 427 },
	{ "Asia/Taipei", 394 },
	{ "Asia/Tashkent", 336 },
	{ "Asia/Tbilisi", 332 },
	{ "Asia/Tehran", 320 },
	{ "Asia/Thimphu", 362 },
	{ "Asia/Tokyo", 399 },
	{ "Asia/Tomsk", 380 },
	{ "Asia/Ulaanbaatar", 395 },
	{ "Asia/Urumqi", 356 },
	{ "Asia/Ust-Nera", 424 },
	{ "Asia/Vientiane", 372 },
	{ "Asia/Vladivostok", 423 },
	{ "Asia/Yakutsk", 406 },
	{ "Asia/Yekaterinburg", 348 },
	{ "Asia/Yerevan", 334 },
	{ "Atlantic/Azores", 179 },
	{ "Atlantic/Bermuda", 107 },
	{ "Atlantic/Canary", 187 },
	{ "Atlantic/Cape_Verde", 181 },
	{ "Atlantic/Faeroe", 188 },
	{ "Atlantic/Madeira", 194 },
	{ "Atlantic/Reykjavik", 195 },
	{ "Atlantic/South_Georgia", 178 },
	{ "Atlantic/Stanley", 156 },
	{ "Atlantic/St_Helena", 205 },
	{ "Australia/Adelaide", 408 },
	{ "Australia/Brisbane", 411 },
	{ "Australia/Broken_Hill", 409 },
	{ "Australia/Currie", 422 },
	{ "Australia/Darwin", 410 },
	{ "Australia/Eucla", 397 },
	{ "Australia/Hobart", 421 },
	{ "Australia/Lindeman", 412 },
	{ "Australia/Lord_Howe", 425 },
	{ "Australia/Melbourne", 414 },
	{ "Australia/Perth", 393 },
	{ "Australia/Sydney", 413 },
	{ "CST6CDT", 65 },
	{ "EST5EDT", 98 },
	{ "Etc/GMT+10", 10 },
	{ "Etc/GMT-10", 420 },
	{ "Etc/GMT+11", 1 },
	{ "Etc/GMT-11", 437 },
	{ "Etc/GMT+1", 182 },
	{ "Etc/GMT+12", 0 },
	{ "Etc/GMT-12", 442 },
	{ "Etc/GMT-1", 258 },
	{ "Etc/GMT-13", 452 },
	{ "Etc/GMT-14", 458 },
	{ "Etc/GMT", 183 },
	{ "Etc/GMT+2", 176 },
	{ "Etc/GMT-2", 281 },
	{ "Etc/GMT+3", 158 },
	{ "Etc/GMT-3", 319 },
	{ "Etc/GMT+4", 143 },
	{ "Etc/GMT-4", 323 },
	{ "Etc/GMT-5", 347 },
	{ "Etc/GMT+5", 82 },
	{ "Etc/GMT-6", 360 },
	{ "Etc/GMT+6", 52 },
	{ "Etc/GMT+7", 34 },
	{ "Etc/GMT-7", 374 },
	{ "Etc/GMT+8", 22 },
	{ "Etc/GMT-8", 392 },
	{ "Etc/GMT+9", 18 },
	{ "Etc/GMT-9", 403 },
	{ "Etc/UTC", 185 },
	{ "Europe/Amsterdam", 223 },
	{ "Europe/Andorra", 213 },
	{ "Europe/Astrakhan", 324 },
	{ "Europe/Athens", 263 },
	{ "Europe/Belgrade", 233 },
	{ "Europe/Berlin", 212 },
	{ "Europe/Bratislava", 235 },
	{ "Europe/Brussels", 237 },
	{ "Europe/Bucharest", 260 },
	{ "Europe/Budapest", 229 },
	{ "Europe/Busingen", 216 },
	{ "Europe/Chisinau", 266 },
	{ "Europe/Copenhagen", 238 },
	{ "Europe/Dublin", 190 },
	{ "Europe/Gibraltar", 217 },
	{ "Europe/Guernsey", 189 },
	{ "Europe/Helsinki", 286 },
	{ "Europe/Isle_of_Man", 191 },
	{ "Europe/Istanbul", 297 },
	{ "Europe/Jersey", 192 },
	{ "Europe/Kaliningrad", 292 },
	{ "Europe/Kiev", 282 },
	{ "Europe/Kirov", 305 },
	{ "Europe/Lisbon", 193 },
	{ "Europe/Ljubljana", 234 },
	{ "Europe/London", 186 },
	{ "Europe/Luxembourg", 220 },
	{ "Europe/Madrid", 239 },
	{ "Europe/Malta", 222 },
	{ "Europe/Mariehamn", 283 },
	{ "Europe/Minsk", 303 },
	{ "Europe/Monaco", 221 },
	{ "Europe/Moscow", 304 },
	{ "Europe/Oslo", 224 },
	{ "Europe/Paris", 236 },
	{ "Europe/Podgorica", 232 },
	{ "Europe/Prague", 231 },
	{ "Europe/Riga", 288 },
	{ "Europe/Rome", 218 },
	{ "Europe/Samara", 327 },
	{ "Europe/San_Marino", 227 },
	{ "Europe/Sarajevo", 242 },
	{ "Europe/Saratov", 331 },
	{ "Europe/Simferopol", 306 },
	{ "Europe/Skopje", 244 },
	{ "Europe/Sofia", 284 },
	{ "Europe/Stockholm", 225 },
	{ "Europe/Tallinn", 285 },
	{ "Europe/Tirane", 230 },
	{ "Europe/Ulyanovsk", 325 },
	{ "Europe/Uzhgorod", 289 },
	{ "Europe/Vaduz", 219 },
	{ "Europe/Vatican", 228 },
	{ "Europe/Vienna", 214 },
	{ "Europe/Vilnius", 287 },
	{ "Europe/Volgograd", 333 },
	{ "Europe/Warsaw", 241 },
	{ "Europe/Zagreb", 243 },
	{ "Europe/Zaporozhye", 290 },
	{ "Europe/Zurich", 215 },
	{ "Indian/Antananarivo", 313 },
	{ "Indian/Chagos", 357 },
	{ "Indian/Christmas", 368 },
	{ "Indian/Cocos", 365 },
	{ "Indian/Comoro", 312 },
	{ "Indian/Kerguelen", 343 },
	{ "Indian/Mahe", 330 },
	{ "Indian/Maldives", 342 },
	{ "Indian/Mauritius", 328 },
	{ "Indian/Mayotte", 318 },
	{ "Indian/Reunion", 329 },
	{ "MST7MDT", 44 },
	{ "Pacific/Apia", 456 },
	{ "Pacific/Auckland", 440 },
	{ "Pacific/Bougainville", 426 },
	{ "Pacific/Chatham", 451 },
	{ "Pacific/Easter", 66 },
	{ "Pacific/Efate", 436 },
	{ "Pacific/Enderbury", 453 },
	{ "Pacific/Fakaofo", 454 },
	{ "Pacific/Fiji", 450 },
	{ "Pacific/Funafuti", 447 },
	{ "Pacific/Galapagos", 48 },
	{ "Pacific/Gambier", 19 },
	{ "Pacific/Guadalcanal", 431 },
	{ "Pacific/Guam", 418 },
	{ "Pacific/Honolulu", 6 },
	{ "Pacific/Johnston", 9 },
	{ "Pacific/Kiritimati", 457 },
	{ "Pacific/Kosrae", 434 },
	{ "Pacific/Kwajalein", 445 },
	{ "Pacific/Majuro", 444 },
	{ "Pacific/Marquesas", 11 },
	{ "Pacific/Midway", 4 },
	{ "Pacific/Nauru", 446 },
	{ "Pacific/Niue", 3 },
	{ "Pacific/Norfolk", 429 },
	{ "Pacific/Noumea", 435 },
	{ "Pacific/Pago_Pago", 2 },
	{ "Pacific/Palau", 401 },
	{ "Pacific/Pitcairn", 23 },
	{ "Pacific/Ponape", 433 },
	{ "Pacific/Port_Moresby", 415 },
	{ "Pacific/Rarotonga", 7 },
	{ "Pacific/Saipan", 419 },
	{ "Pacific/Tahiti", 8 },
	{ "Pacific/Tarawa", 443 },
	{ "Pacific/Tongatapu", 455 },
	{ "Pacific/Truk", 417 },
	{ "Pacific/Wake", 448 },
	{ "Pacific/Wallis", 449 },
	{ "PST8PDT", 28 },
};
