import org.gradle.api.file.Directory
import org.gradle.api.file.RegularFile
import java.io.File
import java.io.PrintStream

/*
 * Copyright 2019-2024 JetBrains s.r.o. and contributors.
 * Use of this source code is governed by the Apache 2.0 License that can be found in the LICENSE.txt file.
 */

private const val pkg = "package kotlinx.datetime.timezones.tzData"

private fun listDirRecursively(currentRoot: File, prefix: String? = null): Sequence<String> = sequence {
    require(currentRoot.isDirectory)
    for (child in currentRoot.listFiles().orEmpty()) {
        val childPath = prefix?.let { "$prefix/${child.name}" } ?: child.name
        if (child.isDirectory) {
            yieldAll(listDirRecursively(child, childPath))
        } else {
            yield(childPath)
        }
    }
}

fun generateTzdbMetainformation(zoneInfoDir: File, outputDir: Directory, version: String) {
    printingTo(outputDir.file("tzMetainformation.kt")) {
        println("/* AUTOGENERATED FROM ZONE INFO DATABASE v.$version */")
        println()
        println(pkg)
        println()
        println("internal val timeZones: Set<String> by lazy { setOf(")
        listDirRecursively(zoneInfoDir).forEach { zoneName ->
            println("    \"$zoneName\",")
        }
        println(")}")
        println()
        println("internal val timeZoneDatabaseVersion: String = \"$version\"")
    }
}

fun generateZoneInfosResources(zoneInfoDir: File, outputDir: Directory, version: String) {
    val header = buildString {
        appendLine("/* AUTOGENERATED FROM ZONE INFO DATABASE v.$version */")
        appendLine()
        append(pkg)
    }

    val timeZoneNamesByData = LinkedHashMap<ContentEqualByteArray, MutableList<String>>()
    listDirRecursively(zoneInfoDir).forEach { zoneName ->
        val bytes = ContentEqualByteArray(zoneInfoDir.resolve(zoneName).readBytes())
        timeZoneNamesByData.getOrPut(bytes) { mutableListOf() }.add(zoneName)
    }

    printingTo(outputDir.file("tzData.kt")) {
        println(header)
        println()
        println("internal fun zoneDataByNameOrNull(name: String): ByteArray? = when(name) {")
        timeZoneNamesByData.entries.forEachIndexed { id, (tzData, fullTzNames) ->
            val tzDataName = "tzData$id"
            printingTo(outputDir.file("$tzDataName.kt")) {
                println(header)
                println()
                println("/* ${fullTzNames.joinToString(", ")} */")
                println("internal val $tzDataName get() = byteArrayOf(")
                for (chunk in tzData.bytes.asIterable().chunked(16)) {
                    print("    ")
                    val chunkText = chunk.joinToString {
                        it.toString().padStart(4, ' ')
                    } + ","
                    println(chunkText)
                }
                println(")")
            }
            fullTzNames.forEach { name ->
                println("    \"$name\" -> $tzDataName")
            }
        }
        println("    else -> null")
        println("}")
    }
}

private class ContentEqualByteArray(val bytes: ByteArray) {
    override fun hashCode(): Int = bytes.contentHashCode()
    override fun equals(other: Any?): Boolean = other is ContentEqualByteArray && other.bytes.contentEquals(bytes)
}

private inline fun printingTo(file: RegularFile, block: PrintStream.() -> Unit) =
    PrintStream(file.asFile.outputStream().buffered(8192)).use { it.block() }
