import org.gradle.api.file.Directory
import java.io.File
import java.io.PrintStream

/*
 * Copyright 2019-2024 JetBrains s.r.o. and contributors.
 * Use of this source code is governed by the Apache 2.0 License that can be found in the LICENSE.txt file.
 */

private const val pkg = "package kotlinx.datetime.timezones.tzData"

private fun generateByteArrayProperty(tzData: TzData, header: String, propertyName: String): String = buildString {
    append(header)
    appendLine()
    appendLine()
    appendLine("/* ${tzData.fullTzNames.joinToString(", ")} */")
    append("internal val $propertyName get() = byteArrayOf(")
    for (chunk in tzData.data.toList().chunked(16)) {
        appendLine()
        append("    ")
        val chunkText = chunk.joinToString {
            it.toString().padStart(4, ' ')
        } + ","
        append(chunkText)
    }
    appendLine()
    append(")")
}

private class TzData(val data: ByteArray, val fullTzNames: MutableList<String>)

private fun listDirRecursively(currentRoot: File, prefix: String? = null): Sequence<String> = sequence {
    require(currentRoot.isDirectory)
    for (child in currentRoot.listFiles()) {
        val childPath = prefix?.let { "$prefix/${child.name}" } ?: child.name
        if (child.isDirectory) {
            yieldAll(listDirRecursively(child, childPath))
        } else {
            yield(childPath)
        }
    }
}

private fun loadTzBinaries(
    tzDirRoot: File,
    result: MutableList<TzData>
) {
    listDirRecursively(tzDirRoot).forEach { zoneName ->
        val zoneInfo = tzDirRoot.resolve(zoneName)
        val bytes = zoneInfo.readBytes()
        val foundTzData = result.firstOrNull { it.data.contentEquals(bytes) }
        val tzData: TzData
        if (foundTzData != null) {
            tzData = foundTzData
        } else {
            tzData = TzData(bytes, mutableListOf())
            result.add(tzData)
        }
        tzData.fullTzNames.add(zoneName)
    }
}

fun generateTzdbMetainformation(zoneInfoDir: File, outputDir: Directory, version: String) {
    PrintStream(outputDir.file("tzMetainformation.kt").asFile.outputStream()).use {
        it.apply {
            println("/* AUTOGENERATED FROM ZONE INFO DATABASE v.$version */")
            println()
            println(pkg)
            println()
            println("internal val timeZones: Set<String> by lazy { setOf(")
            listDirRecursively(zoneInfoDir).forEach { zoneName ->
                println("    \"$zoneName\",")
            }
            println(")}")
            println()
            println("internal val timeZoneDatabaseVersion: String = \"$version\"")
        }
    }
}

fun generateZoneInfosResources(zoneInfoDir: File, outputDir: Directory, version: String) {
    val header = buildString {
        appendLine()
        append("/* AUTOGENERATED FROM ZONE INFO DATABASE v.$version */")
        appendLine()
        appendLine()
        append(pkg)
    }

    val loadedZones = mutableListOf<TzData>()
    loadTzBinaries(zoneInfoDir, loadedZones)

    val zoneDataByNameBody = StringBuilder()
    val getTimeZonesBody = StringBuilder()
    loadedZones.forEachIndexed { id, tzData ->
        val tzDataName = "tzData$id"
        val data = generateByteArrayProperty(tzData, header, tzDataName)
        outputDir.file("$tzDataName.kt").asFile.writeText(data)
        tzData.fullTzNames.forEach { name ->
            zoneDataByNameBody.appendLine("    \"$name\" -> $tzDataName")
            getTimeZonesBody.appendLine("    \"$name\",")
        }
    }

    val content = buildString {
        append(header)
        appendLine()
        appendLine()
        appendLine("internal fun zoneDataByNameOrNull(name: String): ByteArray? = when(name) {")
        append(zoneDataByNameBody)
        appendLine()
        append("    else -> null")
        appendLine()
        append("}")
        appendLine()
    }

    outputDir.file("tzData.kt").asFile.writeText(content)
}
